// GENERATED FILE - DO NOT EDIT.
//
// Source:     referencias/unicode/ucd.nounihan.flat.xml
// UCD:        17.0.0
// Regenerate: dart run tool/generate_unicode_tables.dart

/// The Unicode case mappings: uppercase, lowercase, titlecase and case folding.
///
/// `toUpperCase` on a Dart `String` is ASCII-only in some contexts and locale
/// blind in all of them, and neither is enough for a text stack: `ß`
/// uppercases to two characters, `ǅ` has a titlecase that is neither its upper
/// nor its lower case, and case-insensitive matching is not "lowercase both
/// sides" - it is case *folding*, a third mapping that exists precisely because
/// lowercasing is not idempotent under comparison.
///
/// ## Simple and full
///
/// Every property comes in two forms. The **simple** mapping is one code point
/// to one code point, which is what a fixed-width buffer and a `cmap` lookup
/// need. The **full** mapping may be longer - `ß` uppercases to `SS`, `ﬀ` folds
/// to `ff` - and is what a correct `toUpperCase` needs.
///
/// The full accessors return null when the full mapping is the same as the
/// simple one, which is the overwhelmingly common case. That is not an oversight
/// to work around; it is the calling convention: ask [fullUppercaseOf] first
/// and fall back to [simpleUppercaseOf]. Returning a one-element list instead
/// would mean an allocation per character for every character in the language.
///
/// ## What is deliberately not here
///
/// **Conditional and locale-sensitive mappings** - `SpecialCasing.txt`. Final
/// sigma (`Σ` lowercases to `ς` at the end of a word and `σ` elsewhere),
/// Lithuanian dot retention, and the Turkish dotted and dotless I. All three
/// need context or a locale, neither of which a per-code-point table has, and a
/// table that pretended otherwise would be wrong in exactly the languages that
/// notice. A caller doing user-visible case conversion for Turkish or
/// Lithuanian must layer those rules on top of this.
///
/// **Case_Ignorable and the derived Changes_When_* properties**, which the
/// conditional rules need. They belong with the rules.
library;

import 'packed_table.dart';

final SparseTable _simpleUpper = SparseTable(_simpleUppercaseTable);
final SparseTable _simpleLower = SparseTable(_simpleLowercaseTable);
final SparseTable _simpleTitle = SparseTable(_simpleTitlecaseTable);
final SparseTable _simpleFold = SparseTable(_simpleCaseFoldingTable);
final PoolTable _fullUpper = PoolTable(_fullUppercaseTable);
final PoolTable _fullLower = PoolTable(_fullLowercaseTable);
final PoolTable _fullTitle = PoolTable(_fullTitlecaseTable);
final PoolTable _fullFold = PoolTable(_fullCaseFoldingTable);

/// Simple_Uppercase_Mapping: the single code point [codePoint] uppercases to,
/// or [codePoint] itself when it has no uppercase.
int simpleUppercaseOf(int codePoint) =>
    _simpleUpper.lookup(codePoint, orElse: codePoint);

/// Simple_Lowercase_Mapping, or [codePoint] itself.
int simpleLowercaseOf(int codePoint) =>
    _simpleLower.lookup(codePoint, orElse: codePoint);

/// Simple_Titlecase_Mapping, or [codePoint] itself.
///
/// Not the same as the uppercase for the digraphs: U+01C4 `Ǆ` uppercases to
/// itself and titlecases to U+01C5 `ǅ`.
int simpleTitlecaseOf(int codePoint) =>
    _simpleTitle.lookup(codePoint, orElse: codePoint);

/// Simple_Case_Folding, or [codePoint] itself.
///
/// The mapping to use for case-insensitive comparison when the result has to
/// stay the same length as the input.
int simpleCaseFoldingOf(int codePoint) =>
    _simpleFold.lookup(codePoint, orElse: codePoint);

/// Uppercase_Mapping when it differs from [simpleUppercaseOf], else null.
List<int>? fullUppercaseOf(int codePoint) => _fullUpper.lookup(codePoint);

/// Lowercase_Mapping when it differs from [simpleLowercaseOf], else null.
List<int>? fullLowercaseOf(int codePoint) => _fullLower.lookup(codePoint);

/// Titlecase_Mapping when it differs from [simpleTitlecaseOf], else null.
List<int>? fullTitlecaseOf(int codePoint) => _fullTitle.lookup(codePoint);

/// Case_Folding when it differs from [simpleCaseFoldingOf], else null.
List<int>? fullCaseFoldingOf(int codePoint) => _fullFold.lookup(codePoint);

/// Simple_Uppercase_Mapping. 1505 entries.
const String _simpleUppercaseTable =
    'hD/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/B'
    'B/BB/BB/B7BuuBrB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB'
    '/BB/BB/BB/BB/BC/BB/BB/BB/BB/BB/BB/BByHCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCB'
    'CBCBCBCBCBCBCBCBCvOCBCBCBDBCBCBCBCBCBCBCBDBCBCBCBCBCBCBCBCBCBCBCBCBCBC'
    'BCBCBCBCBCBCBCBCBDBCBCBB3SBmMDBCBDBEBGBDiGEBBmKBikzCDkIDBCBCBDBFBDBEBC'
    'BDBEBCwDGBBDCBBDCBBDCBCBCBCBCBCBCBCBB9ECBCBCBCBCBCBCBCBCBDBBDCBEBCBCBC'
    'BCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBEBCBCBCBCBCBCBCBCBJBD+jVB+jVCBFBCBCBC'
    'BCBB+hVB4hVB8hVBjNB7MC5MB5MCzMC1MB+0yCE5MB20yCC9MBu2yCBwyyCBo0yCChNBlN'
    'Bo0yCBu/UBi0yCDlNC6/UBpNDrNIu+UDzNCm0yCBzNE0yyCBzNBpEBxNBxNBtEG1NLqxyC'
    'BkxyCnFoFsBBCBEBEkIBkIBkIvBrCBpCBpCBpCC/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/'
    'BB/BB/BB/BB/BB/BB/BB9BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/DB9DB9DC7DBxDE9CBrD'
    'BPCBCBCBCBCBCBCBCBCBCBCBCBBrFB/EBOBnHC/FDBDB1B/BB/BB/BB/BB/BB/BB/BB/BB'
    '/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/'
    'BB/EB/EB/EB/EB/EB/EB/EB/EB/EB/EB/EB/EB/EB/EB/EB/ECBCBCBCBCBCBCBCBCBCBC'
    'BCBCBCBCBCBCBKBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBDBC'
    'BCBCBCBCBCBBdCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBC'
    'BCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCByB/CB/CB/CB/CB/CB/CB/CB/CB/CB/C'
    'B/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB'
    '/CB/CB/CB/CB/Cq6Cg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg'
    '8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8F'
    'Bg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FBg8FDg8FBg8FBg8F5XPBPBPBPB'
    'PBPjkC7mMB5mMBnmMBjmMBjmMBlmMB3lMBpiMBk8kCCBvHoglCEsuHRwjlCzDBCBCBCBCB'
    'CBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCB'
    'CBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCB'
    'G1DGBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBC'
    'BCBCBCBCBCBCBCBCBCBCBCBCBCBCBBQBQBQBQBQBQBQBQJQBQBQBQBQBQLQBQBQBQBQBQB'
    'QBQJQBQBQBQBQBQBQBQJQBQBQBQBQBQMQCQCQCQJQBQBQBQBQBQBQBQJ0EB0EBsFBsFBsF'
    'BsFBoGBoGBgIBgIBgHBgHB8HB8HDQBQBQBQBQBQBQBQJQBQBQBQBQBQBQBQJQBQBQBQBQB'
    'QBQBQJQBQCSLpiOFSNQBQPQBQEOOS7K3BiBfBfBfBfBfBfBfBfBfBfBfBfBfBfBfBfFBsa'
    'zBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBBz'
    'BBzBBzBn6B/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB'
    '/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/'
    'CB/CB/CB/CB/CCBE1iVBviVCBCBCBHBDBLBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBC'
    'BCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBJBCBFBN'
    '/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/l'
    'OB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB'
    '/lOB/lOB/lOC/lOG/lO0oeBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBUBC'
    'BCBCBCBCBCBCBCBCBCBCBCBCBoEBCBCBCBCBCBCBEBCBCBCBCBCBCBCBCBCBCBCBCBCBCB'
    'CBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBLBCBDBCBCBCBCBFBFBCBBgDDBCBCBCBCBCBCBC'
    'BCBCBMBCBCBCBCBCBCBCBFBCBDBCBCBCBCBCBCBCBbB9a/5Bd/8rCB/8rCB/8rCB/8rCB/'
    '8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/'
    '8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/'
    '8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/'
    '8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/'
    '8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/'
    '8rCB/8rCB/8rCB/8rCB/8rCB/8rCi8U/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB'
    '/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BumBvCBvCBvCBvCBvCBvCBvCBvCBvCBvC'
    'BvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCB'
    'vCBvCBvCBvCBvCBvCBvCpEvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCB'
    'vCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvC8EtCBtCBtCB'
    'tCBtCBtCBtCBtCBtCBtCBtCCtCBtCBtCBtCBtCBtCBtCBtCBtCBtCBtCBtCBtCBtCBtCCt'
    'CBtCBtCBtCBtCBtCBtCCtCBtCk4B/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB'
    '/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/'
    'DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/D+D/BB/BB/BB/BB/BB/BB/BB/BB/BB/'
    'BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/B75C/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB'
    '/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BhsV/B'
    'B/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB'
    '/BB/BB/BB/BB/BB/BB/BB/B8B1BB1BB1BB1BB1BB1BB1BB1BB1BB1BB1BB1BB1BB1BB1BB'
    '1BB1BB1BB1BB1BB1BB1BB1BB1BB1BvyejCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjC'
    'BjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjC';

/// Simple_Lowercase_Mapping. 1488 entries.
const String _simpleLowercaseTable =
    'hCgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgC'
    'BgCBgCBgCmDgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgC'
    'BgCBgCBgCCgCBgCBgCBgCBgCBgCBgCiBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
    'CCCCCCCCCCtMCCCCCCDCCCCCCCCCCCCCCCDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
    'CCCCCCCCCCCxHBCCCCCEkNBCCCC8MBCC6MB6MBCD+EB0MB2MBCC6MB+MCmNBiNBCEmNBqN'
    'CsNBCCCCCC0NBCC0NDCC0NBCCyNByNBCCCC2NBCECIEBCCEBCCEBCCCCCCCCCCCCCCCCCD'
    'CCCCCCCCCCCCCCCCCDEBCCCChGBvDBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
    'jICCCCCCCCCCCCCCCCCCI2iVBCClKBwiVDCClMBqEBuEBCCCCCCCCCiJCCCECJoHHsCCqC'
    'BqCBqCCgEC+DB+DCgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCCgCB'
    'gCBgCBgCBgCBgCBgCBgCBgCkBQJCCCCCCCCCCCCCCCCCCCCCCCG3DDCCNBCDjIBjIBjIBg'
    'FBgFBgFBgFBgFBgFBgFBgFBgFBgFBgFBgFBgFBgFBgFBgFBgCBgCBgCBgCBgCBgCBgCBgC'
    'BgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCB'
    'gCxBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
    'CCCCCCCCCCCCCCCCCCCCCCeBCCCCCCCCCCCCCDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDgDBgDB'
    'gDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBg'
    'DBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDq6CgmOBgmOBgmOBgmOBgmOBgmOBgmOBgm'
    'OBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOB'
    'gmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOCgmOGgmOzWg9rCBg9rC'
    'Bg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rC'
    'Bg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rC'
    'Bg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rC'
    'Bg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rC'
    'Bg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rC'
    'Bg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBg9rCBQBQBQBQBQBQ0kCCH/7FB/7FB/7FB/'
    '7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7F'
    'B/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/'
    '7FB/7FB/7FB/7FB/7FD/7FB/7FB/7FhKCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCK97OCCCCCCCCCCCCCCCCCCCCCCCCC'
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
    'CKPBPBPBPBPBPBPBPJPBPBPBPBPBPLPBPBPBPBPBPBPBPJPBPBPBPBPBPBPBPJPBPBPBPB'
    'PBPMPCPCPCPJPBPBPBPBPBPBPBPZPBPBPBPBPBPBPBPJPBPBPBPBPBPBPBPJPBPBPBPBPB'
    'PBPBPJPBPBzEBzEBRMrFBrFBrFBrFBRMPBPBnGBnGNPBPB/GB/GBNM/HB/HB7HB7HBRqJ5'
    '1OE9rQBrkQH4BuBgBBgBBgBBgBBgBBgBBgBBgBBgBBgBBgBBgBBgBBgBBgBBgBUCzZ0BB0'
    'BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0B'
    'B0Bx5BgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBg'
    'DBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgD'
    'BgDBgDBgDxBCCt/UBruHBt+UDCCCCCC3hVB5/UB9hVB7hVCCDCJ9jVB9jVBCCCCCCCCCCC'
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
    'CCCCCCCCCCCCCCCCCCJCCCFCuqeCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
    'CCUCCCCCCCCCCCCCCCCCCCCCCCCCCCoECCCCCCCCCCCCCECCCCCCCCCCCCCCCCCCCCCCCC'
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCLCCCCnglCBCCCCCCCCCFCCvyyCDCCCECC'
    'CCCCCCCCCCCCCCCCCCn0yCB90yCB10yCBh0yCBn0yCCjxyCBzyyCBpxyCBg6BBCCCCCCCC'
    'CCCCCCCC/CBl0yCBvjlCBCCCCt2yCBCCCCCCCCCCCCCCCChkzCZCs5VgCBgCBgCBgCBgCB'
    'gCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCmmBwCBwC'
    'BwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCB'
    'wCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCpEwCBwCBwCBwCBwCBwCBwCBwCB'
    'wCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBw'
    'CBwCBwCBwCBwC9EuCBuCBuCBuCBuCBuCBuCBuCBuCBuCBuCCuCBuCBuCBuCBuCBuCBuCBu'
    'CBuCBuCBuCBuCBuCBuCBuCCuCBuCBuCBuCBuCBuCBuCCuCBuCr3BgEBgEBgEBgEBgEBgEB'
    'gEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBg'
    'EBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgE+EgCBg'
    'CBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgC75CgCBgCB'
    'gCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBg'
    'CBgCBgCBgCBgCBgCBgChsVgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCB'
    'gCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgChC2BB2BB2BB2BB2BB2BB2BB'
    '2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BoyekCBkCBkCBkCBkC'
    'BkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCB'
    'kCBkCBkCBkCBkCBkC';

/// Simple_Titlecase_Mapping. 1459 entries.
const String _simpleTitlecaseTable =
    'hD/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/B'
    'B/BB/BB/B7BuuBrB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB'
    '/BB/BB/BB/BB/BC/BB/BB/BB/BB/BB/BB/BByHCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCB'
    'CBCBCBCBCBCBCBCBCvOCBCBCBDBCBCBCBCBCBCBCBDBCBCBCBCBCBCBCBCBCBCBCBCBCBC'
    'BCBCBCBCBCBCBCBCBDBCBCBB3SBmMDBCBDBEBGBDiGEBBmKBikzCDkIDBCBCBDBFBDBEBC'
    'BDBEBCwDFCCBBCCBBCCBCBCBCBCBCBCBCBCBB9ECBCBCBCBCBCBCBCBCBCCCBCBEBCBCBC'
    'BCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBEBCBCBCBCBCBCBCBCBJBD+jVB+jVCBFBCBCBC'
    'BCBB+hVB4hVB8hVBjNB7MC5MB5MCzMC1MB+0yCE5MB20yCC9MBu2yCBwyyCBo0yCChNBlN'
    'Bo0yCBu/UBi0yCDlNC6/UBpNDrNIu+UDzNCm0yCBzNE0yyCBzNBpEBxNBxNBtEG1NLqxyC'
    'BkxyCnFoFsBBCBEBEkIBkIBkIvBrCBpCBpCBpCC/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/'
    'BB/BB/BB/BB/BB/BB/BB9BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/DB9DB9DC7DBxDE9CBrD'
    'BPCBCBCBCBCBCBCBCBCBCBCBCBBrFB/EBOBnHC/FDBDB1B/BB/BB/BB/BB/BB/BB/BB/BB'
    '/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/'
    'BB/EB/EB/EB/EB/EB/EB/EB/EB/EB/EB/EB/EB/EB/EB/EB/ECBCBCBCBCBCBCBCBCBCBC'
    'BCBCBCBCBCBCBKBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBDBC'
    'BCBCBCBCBCBBdCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBC'
    'BCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCByB/CB/CB/CB/CB/CB/CB/CB/CB/CB/C'
    'B/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB'
    '/CB/CB/CB/CB/CyzDPBPBPBPBPBPjkC7mMB5mMBnmMBjmMBjmMBlmMB3lMBpiMBk8kCCBv'
    'HoglCEsuHRwjlCzDBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBC'
    'BCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBC'
    'BCBCBCBCBCBCBCBCBCBCBCBCBG1DGBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCB'
    'CBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBBQBQBQBQBQBQBQBQ'
    'JQBQBQBQBQBQLQBQBQBQBQBQBQBQJQBQBQBQBQBQBQBQJQBQBQBQBQBQMQCQCQCQJQBQBQ'
    'BQBQBQBQBQJ0EB0EBsFBsFBsFBsFBoGBoGBgIBgIBgHBgHB8HB8HDQBQBQBQBQBQBQBQJQ'
    'BQBQBQBQBQBQBQJQBQBQBQBQBQBQBQJQBQCSLpiOFSNQBQPQBQEOOS7K3BiBfBfBfBfBfB'
    'fBfBfBfBfBfBfBfBfBfBfFBsazBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBB'
    'zBBzBBzBBzBBzBBzBBzBBzBBzBBzBBzBn6B/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/C'
    'B/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB'
    '/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CB/CCBE1iVBviVCBCBCBHBDBLBCBCBCBCBCB'
    'CBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCB'
    'CBCBCBCBCBCBCBCBCBJBCBFBN/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/'
    'lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lO'
    'B/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOB/lOC/lOG/lO0oeBCBCBCBCBCBCBCBCBCBCBCB'
    'CBCBCBCBCBCBCBCBCBCBCBUBCBCBCBCBCBCBCBCBCBCBCBCBCBoEBCBCBCBCBCBCBEBCBC'
    'BCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBLBCBDBCBCBCBC'
    'BFBFBCBBgDDBCBCBCBCBCBCBCBCBCBMBCBCBCBCBCBCBCBFBCBDBCBCBCBCBCBCBCBbB9a'
    '/5Bd/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/'
    '8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/'
    '8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/'
    '8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/'
    '8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/'
    '8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCi8U/BB/BB/BB/BB/B'
    'B/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BumBvCBv'
    'CBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvC'
    'BvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCpEvCBvCBvCBvCBvCBvCBvCBvC'
    'BvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCBvCB'
    'vCBvCBvCBvCBvC8EtCBtCBtCBtCBtCBtCBtCBtCBtCBtCBtCCtCBtCBtCBtCBtCBtCBtCB'
    'tCBtCBtCBtCBtCBtCBtCBtCCtCBtCBtCBtCBtCBtCBtCCtCBtCk4B/DB/DB/DB/DB/DB/D'
    'B/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB'
    '/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/DB/D+D/BB'
    '/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/B75C/BB/B'
    'B/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB'
    '/BB/BB/BB/BB/BB/BB/BhsV/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/B'
    'B/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/BB/B8B1BB1BB1BB1BB1BB1BB1B'
    'B1BB1BB1BB1BB1BB1BB1BB1BB1BB1BB1BB1BB1BB1BB1BB1BB1BB1BvyejCBjCBjCBjCBj'
    'CBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjCBjC'
    'BjCBjCBjCBjCBjCBjC';

/// Simple_Case_Folding. 1512 entries.
const String _simpleCaseFoldingTable =
    'hCgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgC'
    'BgCBgCBgC7CuwBLgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBg'
    'CBgCBgCBgCBgCCgCBgCBgCBgCBgCBgCBgCiBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
    'CCCCCCCCCCCCCECCCCCDCCCCCCCCCCCCCCCDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
    'CCCCCCCCCCCCxHBCCCCCC3QCkNBCCCC8MBCC6MB6MBCD+EB0MB2MBCC6MB+MCmNBiNBCEm'
    'NBqNCsNBCCCCCC0NBCC0NDCC0NBCCyNByNBCCCC2NBCECIEBCCEBCCEBCCCCCCCCCCCCCC'
    'CCCDCCCCCCCCCCCCCCCCCDEBCCCChGBvDBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
    'CCCCjICCCCCCCCCCCCCCCCCCI2iVBCClKBwiVDCClMBqEBuEBCCCCCCCCC3HoHrBCCCECJ'
    'oHHsCCqCBqCBqCCgEC+DB+DCgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBg'
    'CBgCCgCBgCBgCBgCBgCBgCBgCBgCBgCXCNQB7BBxBEdBrBCCCCCCCCCCCCCCCCCCCCCCCC'
    'CrDB/CD3DB/DCCCNBCDjIBjIBjIBgFBgFBgFBgFBgFBgFBgFBgFBgFBgFBgFBgFBgFBgFB'
    'gFBgFBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBg'
    'CBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCxBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCC'
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCeBCCCCCCCCCCCCCDCCC'
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
    'CCCCCCCCCCCCCCCCCCCCCCDgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgD'
    'BgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDq6Cg'
    'mOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmO'
    'BgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBgmOBg'
    'mOBgmOBgmOCgmOGgmOrZPBPBPBPBPBPjkC7kMB5kMBnkMBjkMBjkMBlkMB3jMBniMBm8kC'
    'BCH/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7F'
    'B/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/'
    '7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FB/7FD/7FB/7FB/7FhKCCCCCCCCCCCCCCCCCCCCCC'
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCHzDD97OCCCCCC'
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
    'CCCCCCCCCCCCCCCCCCCCKPBPBPBPBPBPBPBPJPBPBPBPBPBPLPBPBPBPBPBPBPBPJPBPBP'
    'BPBPBPBPBPJPBPBPBPBPBPMPCPCPCPJPBPBPBPBPBPBPBPZPBPBPBPBPBPBPBPJPBPBPBP'
    'BPBPBPBPJPBPBPBPBPBPBPBPJPBPBzEBzEBRCpgOKrFBrFBrFBrFBRHlkOFPBPBnGBnGIl'
    'jOFPBPB/GB/GBNM/HB/HB7HB7HBRqJ51OE9rQBrkQH4BuBgBBgBBgBBgBBgBBgBBgBBgBB'
    'gBBgBBgBBgBBgBBgBBgBBgBUCzZ0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0'
    'BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0BB0Bx5BgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDB'
    'gDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBg'
    'DBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDBgDxBCCt/UBruHBt+UDCCCCCC3hVB5/UB'
    '9hVB7hVCCDCJ9jVB9jVBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCJCCCFCuqeCCCCCCCCCCCC'
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCUCCCCCCCCCCCCCCCCCCCCCCCCCCCoECCCCCCC'
    'CCCCCCECCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCLC'
    'CCCnglCBCCCCCCCCCFCCvyyCDCCCECCCCCCCCCCCCCCCCCCCCn0yCB90yCB10yCBh0yCBn'
    '0yCCjxyCBzyyCBpxyCBg6BBCCCCCCCCCCCCCCCC/CBl0yCBvjlCBCCCCt2yCBCCCCCCCCC'
    'CCCCCCChkzCZC7b/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB'
    '/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB'
    '/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB'
    '/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB'
    '/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB'
    '/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCB/8rCm6TC8g'
    'BgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCB'
    'gCBgCBgCmmBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwC'
    'BwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCpEwCBwCBwC'
    'BwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCBwCB'
    'wCBwCBwCBwCBwCBwCBwCBwCBwCBwC9EuCBuCBuCBuCBuCBuCBuCBuCBuCBuCBuCCuCBuCB'
    'uCBuCBuCBuCBuCBuCBuCBuCBuCBuCBuCBuCBuCCuCBuCBuCBuCBuCBuCBuCCuCBuCr3BgE'
    'BgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEB'
    'gEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBgEBg'
    'EBgEBgEBgE+EgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBg'
    'CBgCBgC75CgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCB'
    'gCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgChsVgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgC'
    'BgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgCBgChC2BB2B'
    'B2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2BB2Bo'
    'yekCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkC'
    'BkCBkCBkCBkCBkCBkCBkCBkCBkCBkCBkC';

/// Uppercase_Mapping, only where it differs from the simple mapping.
/// 102 entries.
const String _fullUppercaseTable =
    'mD8G/GC3I3IqDCmX1PnFCra4RgNDSvI9IgBDVvK9K3OCjFpDvoGC7kPp2NBClkP94NBChk'
    'P74NBC/jP94NBCxlP39N2FC16N5jOCD56N9jOjlOCD96NhkOllOCDh7NlkOnhOqBCvHt+N'
    'BCvHv+NBCvHx+NBCvHz+NBCvH1+NBCvH3+NBCvH5+NBCvH7+NBC/H9+NBC/H/+NBC/Hh/N'
    'BC/Hj/NBC/Hl/NBC/Hn/NBC/Hp/NBC/Hr/NBCvGt/NBCvGv/NBCvGx/NBCvGz/NBCvG1/N'
    'BCvG3/NBCvG5/NBCvG7/NBC/G9/NBC/G//NBC/GhgOBC/GjgOBC/GlgOBC/GngOBC/GpgO'
    'BC/GrgOBCvDtgOBCvDvgOBCvDxgOBCvDzgOBCvD1gOBCvD3gOBCvD5gOBCvD7gOBC/D9gO'
    'BC/D/gOBC/DhhOBC/DjhOBC/DlhOBC/DnhOBC/DphOBC/DrhODCQxhOBCjiOzhOBC7iO1h'
    'OCCpiOnnOBDriOpnO7hOFC1iOliOGCQxiOBC3iOziOBC1jO1iOCC9iOnoOBD/iOpoO7iOF'
    'CpjOljOGDxjOzsOjtOBDzjO1sOjtODC5jOnpOBD7jO9sOppOLD5jOztOjuOBD7jO1tOjuO'
    'BClkOhtOCChkOnqOBDjkO9tOpqOLCQxlOBCzkOzlOBCpmO1lOCC5kOnrOBD7kOprO7lOFC'
    'llOlmOk42BCzr9Dzr9DBC1r9Dvr9DBC3r9Drr9DBD5r9D5r9Dzr9DBD7r9D7r9Dvr9DBCj'
    'r9Dhr9DBClr9Djr9DNC986D586DBC/86D996DBCh96Dz96DBCv86D/86DBCl96Dz96D';

/// Lowercase_Mapping, only where it differs from the simple mapping.
/// 1 entries.
const String _fullLowercaseTable = 'BCwJCtMud';

/// Titlecase_Mapping, only where it differs from the simple mapping.
/// 48 entries.
const String _fullTitlecaseTable =
    'wBwD/GC3I3GqDCmX1PnFCra4RgNDSvI9IgBDVvK9K3OCjFJvoGC7kPp2NBClkP94NBChkP'
    '74NBC/jP94NBCxlP39N2FC16N5jOCD56N9jOjlOCD96NhkOllOCDh7NlkOnhO8CCQ5mOCC'
    '7iO9mOCCpiOnnOBDriOpnOjnOLCQ5nOCC1jO9nOCC9iOnoOBD/iOpoOjoOLDxjOzsOjtOB'
    'DzjO1sOjtODC5jOnpOBD7jO9sOppOLD5jOztOjuOBD7jO1tOjuOBClkOhtOCChkOnqOBDj'
    'kO9tOpqOLCQ5qOCCpmO9qOCC5kOnrOBD7kOprOjrOp42BCzr9Dzp9DBC1r9Dvp9DBC3r9D'
    'rp9DBD5r9D5p9Dzp9DBD7r9D7p9Dvp9DBCjr9Dhp9DBClr9Djp9DNC986D556DBC/86D96'
    '6DBCh96Dz66DBCv86D/56DBCl96Dz66D';

/// Case_Folding, only where it differs from the simple mapping.
/// 104 entries.
const String _fullCaseFoldingTable =
    'oDgH/GC3G3GxCCtMudZCmX1NnFCrY4RgNDyCvI9IgBDqBvK9K3OCjCJvoGC7iPp2NBCliP'
    '94NBChiP74NBC/hP94NBCxjP39NEC1iP1iPyFC14N5jOCD54N9jOjlOCD94NhkOllOCDh5'
    'NlkOnhOqBC/Ht8NBC/Hv8NBC/Hx8NBC/Hz8NBC/H18NBC/H38NBC/H58NBC/H78NBCvI98'
    'NBCvI/8NBCvIh9NBCvIj9NBCvIl9NBCvIn9NBCvIp9NBCvIr9NBC/Gt9NBC/Gv9NBC/Gx9'
    'NBC/Gz9NBC/G19NBC/G39NBC/G59NBC/G79NBCvH99NBCvH/9NBCvHh+NBCvHj+NBCvHl+'
    'NBCvHn+NBCvHp+NBCvHr+NBC/Dt+NBC/Dv+NBC/Dx+NBC/Dz+NBC/D1+NBC/D3+NBC/D5+'
    'NBC/D7+NBCvE9+NBCvE/+NBCvEh/NBCvEj/NBCvEl/NBCvEn/NBCvEp/NBCvEr/NDCjEx/'
    'NBCjgOz/NBCvgO1/NCCpgOnnOBDrgOpnO7/NFC1gOlgOGC7ExgOBC3gOzgOBCrhO1gOCC9'
    'gOnoOBD/gOpoO7gOFCphOlhOGDxhOzsOjtOBDzhO1sOjtODC5hOnpOBD7hO9sOppOLD5hO'
    'ztOjuOBD7hO1tOjuOBCliOhtOCChiOnqOBDjiO9tOpqOLCrHxjOBCziOzjOBCriO1jOCC5'
    'iOnrOBD7iOprO7jOFCljOlkOk42BCzp9Dzp9DBC1p9Dvp9DBC3p9Drp9DBD5p9D5p9Dzp9'
    'DBD7p9D7p9Dvp9DBCjp9Dhp9DBClp9Djp9DNC956D556DBC/56D966DBCh66Dz66DBCv56'
    'D/56DBCl66Dz66D';
