// GENERATED FILE - DO NOT EDIT.
//
// Source:     referencias/unicode/ucd.nounihan.flat.xml
// UCD:        17.0.0
// Regenerate: dart run tool/generate_unicode_tables.dart

/// Word_Break (`WB`), the property table behind UAX #29 word segmentation.
///
/// This is the data a double-click needs, and the data `Ctrl+Left` needs, and
/// the data a spell checker needs to know where one word stops. Splitting on
/// spaces gets all three wrong the moment the text contains `don't`, `3.14`,
/// `C++` or any Japanese at all.
///
/// ## Scope
///
/// This file is the **property table only**; the WB1-WB999 rules that consume
/// it are not here. That is deliberate: the rules need a scanner with the same
/// shape as the one in `grapheme.dart`, and putting the table in first means
/// the shaper and the caret code can use Word_Break for the things it answers
/// directly - is this character a letter, a number, a Katakana - before the
/// segmenter exists.
///
/// ## Coverage
///
/// Total over U+0000..U+10FFFF. Unassigned code points read as
/// [WordBreak.other], which the rules treat as a word boundary on both sides.
library;

import 'packed_table.dart';

/// Word_Break property values, named after their UAX #29 long aliases.
///
/// The member order is the one the generated table encodes. Reordering the
/// members silently re-labels every code point, so the enum and the table
/// are generated together and have to be regenerated together.
enum WordBreak {
  /// Anything the rules do not name.
  other,

  /// U+000D.
  cr,

  /// U+000A.
  lf,

  /// U+000B, U+000C, U+0085, U+2028, U+2029.
  newline,

  /// Grapheme_Extend, which never starts a word.
  extend,

  /// U+200D.
  zwj,

  /// Format characters other than ZWJ and ZWNJ.
  format,

  /// One half of a flag.
  regionalIndicator,

  /// Katakana, which words together as a block.
  katakana,

  /// Hebrew letters, separated from ALetter for the single quote rules
  /// WB7a and WB7b - Hebrew uses U+0027 inside words.
  hebrewLetter,

  /// Ordinary word-forming letters.
  aLetter,

  /// U+0027.
  singleQuote,

  /// U+0022.
  doubleQuote,

  /// Joins letters and numbers alike, like U+002E.
  midNumLet,

  /// Joins letters only, like U+00B7.
  midLetter,

  /// Joins numbers only, like U+002C.
  midNum,

  /// Digits.
  numeric,

  /// U+005F and friends, which glue words.
  extendNumLet,

  /// Ordinary space, which WB3d keeps together.
  wSegSpace;
}

final RangeTable _wordBreaks = RangeTable(_wordBreakTable);

/// The Word_Break value of [codePoint].
WordBreak wordBreakOf(int codePoint) =>
    WordBreak.values[_wordBreaks.lookup(codePoint)];

/// Word_Break for the whole code space. 1909 runs.
const String _wordBreakTable =
    'AAKCBDCBBASSBABMBAELBAEPBABNBABQKOBPBAFKaAERBABKaAKDBAkBKBACGBAHKBABOB'
    'KBABKBAFKXABKfABKgPAGKiBEwDKFABKCACKEPBKBAGKBOBKDABKBABKUABKzCABKrEABE'
    'HKmFABKmBACKEABKBOBKpBPBKBAGEtBABEBABECABECABEBAIJbAEJEKBOBALQGAGPCACE'
    'LABGBADKrBEVQKABQBPBABKCEBKjDABKBEHQBABEGKCECABEEKCQKKDACKBAPKCEBKeEbA'
    'CK5CELKBAOQKKhBEJKCACPBABKBACEBACKWEEKBEJKBEDKBEFASKZEDAEKLAFKYABKHQCA'
    'FEJKqBEYQBEhBK2BEDKBESKBEHKKECACQKABKQEDABKIACKCACKWABKHABKBADKEACEBKB'
    'EHACECACEDKBAIEBAEKCABKDECACQKKCAKKBABEBACEDABKGAEKCACKWABKHABKCABKCAB'
    'KCACEBABEFAEECACEDADEBAHKEABKBAHQKECKDEBALEDABKJABKDABKWABKHABKCABKFAC'
    'EBKBEIABEDABEDACKBAPKCECACQKAJKBEGABEDABKIACKCACKWABKHABKCABKFACEBKBEH'
    'ACECACEDAHEDAEKCABKDECACQKABKBAQEBKBABKGADKDABKEADKCABKBABKCADKCADKDAD'
    'KMAEEFADEDABEEACKBAGEBAOQKAQEFKIABKDABKXABKQACEBKBEHABEDABEEAHECABKDAB'
    'KCACKCECACQKAQKBEDABKIABKDABKXABKKABKFACEBKBEHABEDABEEAHECAFKDABKCECAC'
    'QKABKCEBAMEEKJABKDABKpBECKBEHABEDABEEKBAFKDEBAHKDECACQKAKKGABEDABKSADK'
    'YABKJABKBACKHADEBAEEGABEBABEIAGQKACECA9BEBACEHAMEIABQKA3CEBACEJALEHABQ'
    'KAmBKBAXECAGQKALEBABEBABEBAEECKIABKkBAEEUABECKFELABEkBAJEBAkDEUABQKAME'
    'EAEEDABEDACEHADEEANEMABEBQKEEACKmBABKBAFKBACKrBABKtKABKEACKHABKBABKEAC'
    'KpBABKEACKhBABKEACKHABKBABKEACKPABK5BABKEACKjCACEDAgBKQAQK2CACKGADKsTA'
    'CKRSBKaAFKrCADKLAHKSEEAJKTEDALKSECAMKNABKDABECAgCEgBAJEBACQKAhBEDGBEBQ'
    'KAGK5CAHKFECKiBEBKBAFKmCAKKfABEMAEEMAKQKAgEQLAlBKXEFA5BEKABEdACEBQKAGQ'
    'KAWEuBACEMAUEFKvBERKIADQKAREJAMEDKeENKCQKKsBEOAMKkBEUAIQKADKDQKKkBACKL'
    'AFKrBACKDAQEDABEVKEEBKGEBKCEDKBAFKgGEgCK2IACKGACKmBACKGACKIABKBABKBABK'
    'BABKfACK1BABKHABKBADKDABKHADKEACKGAEKNAFKDABKHADSHABSDABEBFBGCAINCAKNB'
    'ACOBDCGFRBAPRCADPBAPRBAKSBGFABGKABKBANKBAQKNAzBEhBARKBAEKBACKKABKBADKF'
    'AGKBABKBABKBABKEABKLACKEAFKFAEKBARKpBAtZK0BA24BKlHAGKEEDKCAMKmBABKBAFK'
    'BACK4BAHKBAPEBKXAJKHABKHABKHABKHABKHABKHABKHABKHABEgBAvBKBAwOSBAEKBAkB'
    'EGABIFAFKCA8CECICADI7CABIEAFKrBABK+CARKgBAwBIQAwGIvBABI4CAolbKtkBAjCKu'
    'BACKtIADKQQKKCAUKvBEEABEKABKfECKwCECAWK1GAUKREBKDEBKEEBKXEFAEEBATK0BAM'
    'ECKyBESAKQKAGESKGADKBABKCEBQKKcEIACKXENAMKdADEEKvBEOAOKBQKALEBAKQKAGKp'
    'BEOAJKDEBKIECACQKAhBEDAyBEBABEDACECAFECABEBAeKLEFACKDECAKKGACKGACKGAJK'
    'HABKHABK6BAGKzDEIABECACQKAGKk9KAMKXAEKxBAk4IKHAMKFAFJBEBJKABJNABJFABJB'
    'ABJCABJCABJKKiDAhBKrLASKgCACK2BAoBKMAEEQADOBAMEQADRCAYRDPBABNBABPBOBAa'
    'KFABKnEACGBAHNBAEPBABNBABQKOBPBAFKaAERBABKaALI4BECKfADKGACKGACKGACKDAc'
    'GDAEKMABKaABKTABKCABKPACKOAiBK7DAlCK1BAoEEBAiEKdADKxBAPEBAfKgBANKeAFKm'
    'BEFAFKeACKkBAEKIABKFAqBK+EACQKAGKkBAEKkBAEKoBAIK0BAMKLABKPABKHABKCABKL'
    'ABKPABKHABKCADK0BAMK3JAJKWAKKIAYKGABKqBABKJAlCKGACKBABKsBABKCADKBACKXA'
    'KKXAJKfAhCKTABKCAKKWAKKaAGKaAmBK4BAGKCAgCKBEDABECAFEEKEABKDABKdACEDAEE'
    'BAgBKdADKdAjBKIABKcECAZK2BAKKWAKKTANKSAuDKpCA3BKzBANKzBANKkBEEAIQKAGQK'
    'KcADEFABKXA6HKqBABECADKCAQKGAyBEGKdAKKBAIKWELAfKSEEAqBKVAbKXAJEDK1BEPA'
    'fQKEBKCECKBAJEEKtBELACQBAEEBAKQBACKZAHQKAGEDKkBEOABQKAEKBECKBAIKjBEBAC'
    'KBAJEDKwBEOKEAEEEABECQKKBABKBAjBKSABKZEMAGEBKCEBA+BKHABKBABKEABKPABKKA'
    'HKvBEMAFQKAGEEABKIACKCACKWABKHABKCABKFABECKBEHACECACEDACKBAGEBAFKFECAC'
    'EHADEFALKKABKBACKBABKmBABKBEJABEBACEBABEEABEFKBEBKBANECAdK1BESKEAFQKAE'
    'EBKDAeKwBEUKCABKBAIQKAmFKvBEHACEJAXKEECAiBKwBERADKBALQKAmBKrBENKBAHQKA'
    'GQUA5BEPAEQKAmGKsBEPAlDKgCQKAVKIACKBACKIABKCABKYEGABECACEEKBEBKBECAMQK'
    'AmCKIACKnBEHACEHKBABKBEBAbKBEKKoBEHKBEEAIEBAIKBELKuBEQADKBASKpCAnDEIA4'
    'CKhBAPQKAGKJABKlBEIABEIKBAPQKAYKeACEWABEOApCKHABKCABKmBEGADEBABECABEHK'
    'BEBAIQKAGKGABKCABKgBEFABECABEFKBAHQKAGKsBAEQKA2HKTEEAJECKBEBKNABKiBEHA'
    'DEFANQKEBA1CKBAvCK6cAmDKvDARKkGAsyCKhDAPKwhBGQEBKGEPAKK78DAFKnSA51GKeE'
    'SQKAm2BK5RAHKfABQKAGKvCABQKAGKeACEFALKwBEHAJKEAMQKAJKVAFKTAwNKtBADQKAm'
    'GKgCAgBKZACKZAsBKrCAEEBKBE3BAHEEKNAgCKCABKBEBALECA+/PIEABIHABICABIBA/I'
    'IDAyBIBAOIEA40CKrDAFKNADKJAHKKADECABGEAsiEQKAmQEuBACEXA+QEFADEGGIEIACE'
    'HAeEEA0EEDA7NK1CABKnCABKCACKBACKCACKEABKMABKBABKHABKhCABKEACKIABKHABKc'
    'ABKEABKFABKBADKHABK0KACKZABKZABKfABKZABKfABKZABKfABKZABKfABKZABKIACQyB'
    'AgQE3BAEEyBAIEBAOEBAWEFABEPAwiBKfAGKGA1GEHABERACEHABECABEFAFK+BAhBEBAw'
    'DKtBADEHKHACQKAEKBAhKKeEBARKsBEEQKA2OKcEEQKA2GKeECKBQKAlGKfABKDEBKCEBK'
    'HECKFEBAIKCAgHKHABKEABKCABKPABKlGALEHApBKkCEHKBAEQKAmlBKEABKbABKCABKBA'
    'CKBABKKABKEABKBABKBAGKBAEKBABKBABKBABKDABKCABKBACKBABKBABKBABKBABKBABK'
    'CABKBACKEABKHABKEABKEABKBABKKABKRAFKDABKFABKRA0TKaAGKaAGKaA8CHaA7PEFAw'
    '/BQKAnghYGBAeEgDAgEEwHA';
