name: dart_ui_workspace
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - poc/poc_01_win32_window
  - poc/poc_04_cpu_raster
  - poc/poc_05_com_direct2d
  - poc/poc_10_event_loop
  - poc/poc_02_x11_window
  - poc/poc_03_appkit_window
  - poc/poc_11_async_image_download
