name: poc_11_async_image_download
description: Responsive Win32 UI with streamed HTTP image download.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  image: ^4.8.0
  poc_01_win32_window: any
  poc_10_event_loop: any

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.0
