name: mvp_04_web_counter
description: MVP-04 Web Canvas
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  mvp_01_win32_counter:
    path: ../mvp_01_win32_counter
  web: ^1.1.0

dev_dependencies:
  test: ^1.25.0
  lints: ^5.1.0
