import 'dart:math' as math;

import '../../geometry/offset.dart';
import '../../geometry/rect.dart';
import 'constants.dart';
import 'document_object.dart';
import 'selectable_objects.dart';
import 'style.dart';

// ---------------------------------------------------------------------------
// PrimitiveObject — base for all drawing primitives
// ---------------------------------------------------------------------------

/// Base class for graphics primitives that have their own geometry.
///
/// Each primitive stores a [trafo] (affine transform) and a [style] (fill +
/// stroke). The geometry is generated by [getInitialPaths] and cached in
/// [cachePaths] after applying the transform.
abstract class PrimitiveObject extends SelectableObject {
  PrimitiveObject({
    super.parent,
    super.trafo,
    super.style,
    List<double>? fillTrafo,
    List<double>? strokeTrafo,
  })  : fillTrafo = fillTrafo ?? [],
        strokeTrafo = strokeTrafo ?? [];

  /// Transform applied to the fill pattern/gradient.
  List<double> fillTrafo;

  /// Transform applied to the stroke (for scalable strokes).
  List<double> strokeTrafo;

  /// Cached paths after generation (pre-transform).
  List<VectorPath>? cachePaths;

  /// Cached line width after stroke transform.
  double? cacheLineWidth;

  @override
  bool get isPrimitive => true;

  /// Generates the raw geometry paths in local coordinates (before [trafo]).
  List<VectorPath> getInitialPaths();

  /// Whether this shape is geometrically closed.
  bool get isClosed => false;

  @override
  void update() {
    cachePaths = getInitialPaths();
    updateStroke();
    updateBbox();
  }

  void updateStroke() {
    if (style.stroke.isNone) return;
    if (strokeTrafo.isEmpty || !style.stroke.scalableStroke) {
      cacheLineWidth = style.stroke.width;
    } else {
      // Compute the effective line width under the stroke transform.
      final p0 = applyTrafoToPoint(Offset.zero, strokeTrafo);
      final p1 = applyTrafoToPoint(const Offset(1, 0), strokeTrafo);
      final coef = pointsDistance(p0, p1);
      cacheLineWidth = style.stroke.width * coef;
    }
  }

  @override
  void updateBbox() {
    if (cachePaths == null || cachePaths!.isEmpty) {
      cacheBbox = Rect.zero;
      return;
    }
    // Compute bounding box from all path points, transformed.
    double minX = double.infinity;
    double minY = double.infinity;
    double maxX = double.negativeInfinity;
    double maxY = double.negativeInfinity;

    for (final path in cachePaths!) {
      for (final point in _allPoints(path)) {
        final tp = applyTrafoToPoint(point, trafo);
        if (tp.dx < minX) minX = tp.dx;
        if (tp.dy < minY) minY = tp.dy;
        if (tp.dx > maxX) maxX = tp.dx;
        if (tp.dy > maxY) maxY = tp.dy;
      }
    }

    if (minX == double.infinity) {
      cacheBbox = Rect.zero;
    } else {
      // Expand by half stroke width.
      final sw = (cacheLineWidth ?? 0) / 2.0;
      cacheBbox = Rect.fromLTRB(minX - sw, minY - sw, maxX + sw, maxY + sw);
    }
  }

  /// Applies [newTrafo] in document space. See [SelectableObject.applyTrafo]
  /// for why the new transform goes on the *left* of the multiplication.
  @override
  void applyTrafo(List<double> newTrafo) {
    trafo = multiplyTrafo(newTrafo, trafo);
    if (fillTrafo.isNotEmpty) {
      fillTrafo = multiplyTrafo(newTrafo, fillTrafo);
    }
    if (strokeTrafo.isNotEmpty) {
      strokeTrafo = multiplyTrafo(newTrafo, strokeTrafo);
      updateStroke();
    }
    updateBbox();
  }

  @override
  DocumentObject? toCurve() {
    final curve = VectorCurve(
      trafo: List.of(trafo),
      style: style.copyWith(),
      paths: cachePaths
              ?.map((p) => VectorPath(
                    start: p.start,
                    points: List.of(p.points),
                    closure: p.closure,
                  ))
              .toList() ??
          [],
    );
    curve.fillTrafo = List.of(fillTrafo);
    curve.strokeTrafo = List.of(strokeTrafo);
    curve.update();
    return curve;
  }

  @override
  void copyFields(DocumentObject target) {
    super.copyFields(target);
    if (target is PrimitiveObject) {
      target.fillTrafo = List.of(fillTrafo);
      target.strokeTrafo = List.of(strokeTrafo);
      target.cacheLineWidth = cacheLineWidth;
    }
  }

  @override
  void clearColorCache() {
    // Clear any pattern image caches.
  }

  /// Extracts all points from a [VectorPath] for bbox computation.
  static Iterable<Offset> _allPoints(VectorPath path) sync* {
    yield path.start;
    for (final pt in path.points) {
      if (pt is CurvePoint) {
        yield pt.control1;
        yield pt.control2;
        yield pt.endpoint;
      } else if (pt is Offset) {
        yield pt;
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Path data types
// ---------------------------------------------------------------------------

/// A single sub-path: a start point, a list of segments, and a closure flag.
class VectorPath {
  VectorPath({
    required this.start,
    List<Object>? points,
    this.closure = PathClosure.opened,
  }) : points = points ?? [];

  /// The starting point of this sub-path.
  Offset start;

  /// Segment points: either [Offset] (line-to) or [CurvePoint] (cubic Bézier).
  List<Object> points;

  /// Whether this sub-path is closed.
  PathClosure closure;

  bool get isOpen => closure == PathClosure.opened;
  bool get isClosed => closure == PathClosure.closed;

  VectorPath copyWith({
    Offset? start,
    List<Object>? points,
    PathClosure? closure,
  }) =>
      VectorPath(
        start: start ?? this.start,
        points: points ?? List.of(this.points),
        closure: closure ?? this.closure,
      );

  @override
  String toString() =>
      'VectorPath(start=$start, ${points.length} segments, $closure)';
}

/// A cubic Bézier curve point with two control handles and a node type.
class CurvePoint {
  const CurvePoint(this.control1, this.control2, this.endpoint,
      [this.nodeType = NodeType.cusp]);

  final Offset control1;
  final Offset control2;
  final Offset endpoint;
  final NodeType nodeType;

  CurvePoint copyWith({
    Offset? control1,
    Offset? control2,
    Offset? endpoint,
    NodeType? nodeType,
  }) =>
      CurvePoint(
        control1 ?? this.control1,
        control2 ?? this.control2,
        endpoint ?? this.endpoint,
        nodeType ?? this.nodeType,
      );

  @override
  String toString() =>
      'CurvePoint($control1 → $control2 → $endpoint, $nodeType)';
}

// ---------------------------------------------------------------------------
// Rectangle
// ---------------------------------------------------------------------------

/// A rectangle with optional rounded corners.
///
/// Defined by a start point (lower-left) and width/height. The [corners]
/// list describes rounding level (0.0–1.0) clockwise from lower-left.
class VectorRectangle extends PrimitiveObject {
  VectorRectangle({
    super.parent,
    super.trafo,
    super.style,
    super.fillTrafo,
    super.strokeTrafo,
    this.startX = 0.0,
    this.startY = 0.0,
    this.rectWidth = 1.0,
    this.rectHeight = 1.0,
    List<double>? corners,
  }) : corners = corners ?? List.of(kCorners);

  double startX;
  double startY;
  double rectWidth;
  double rectHeight;

  /// Corner rounding `[lowerLeft, upperLeft, upperRight, lowerRight]`, 0.0–1.0.
  List<double> corners;

  @override
  bool get isRect => true;

  @override
  bool get isClosed => true;

  /// Sets geometry from a `[x, y, w, h]` list.
  void setRect(List<double> rect) {
    startX = rect[0];
    startY = rect[1];
    rectWidth = rect[2];
    rectHeight = rect[3];
  }

  /// Returns geometry as `[x, y, w, h]`.
  List<double> getRect() => [startX, startY, rectWidth, rectHeight];

  @override
  List<VectorPath> getInitialPaths() {
    return _getRectPaths(startX, startY, rectWidth, rectHeight, corners);
  }

  /// The four corner points before rounding.
  List<Offset> get cornerPoints => [
        Offset(startX, startY),
        Offset(startX, startY + rectHeight),
        Offset(startX + rectWidth, startY + rectHeight),
        Offset(startX + rectWidth, startY),
      ];

  @override
  DocumentObject createEmpty() => VectorRectangle();

  @override
  void copyFields(DocumentObject target) {
    super.copyFields(target);
    if (target is VectorRectangle) {
      target.startX = startX;
      target.startY = startY;
      target.rectWidth = rectWidth;
      target.rectHeight = rectHeight;
      target.corners = List.of(corners);
    }
  }

  @override
  String toString() =>
      'VectorRectangle(${startX.toStringAsFixed(1)}, ${startY.toStringAsFixed(1)}, '
      '${rectWidth.toStringAsFixed(1)}×${rectHeight.toStringAsFixed(1)})';
}

// ---------------------------------------------------------------------------
// Circle / Ellipse
// ---------------------------------------------------------------------------

/// A circle or ellipse, possibly an arc or sector.
///
/// The initial shape is a unit circle centered at (0.5, 0.5). The [trafo]
/// maps it to the desired position, size, and aspect ratio.
class VectorCircle extends PrimitiveObject {
  VectorCircle({
    super.parent,
    super.trafo,
    super.style,
    super.fillTrafo,
    super.strokeTrafo,
    this.angle1 = 0.0,
    this.angle2 = 0.0,
    this.arcType = ArcType.chord,
    List<double>? initialTrafo,
  }) : initialTrafo = initialTrafo ?? List.of(kNormalTrafo);

  /// Start angle (radians) for arc/sector.
  double angle1;

  /// End angle (radians) for arc/sector.
  double angle2;

  /// Type of arc (chord, pie, open arc).
  ArcType arcType;

  /// Initial transform that maps the unit circle to the desired ellipse.
  List<double> initialTrafo;

  @override
  bool get isCircle => true;

  @override
  bool get isClosed => arcType != ArcType.arc;

  /// Creates from a bounding rect `[cx, cy, w, h]`.
  factory VectorCircle.fromRect(
    List<double> rect, {
    double angle1 = 0.0,
    double angle2 = 0.0,
    ArcType arcType = ArcType.chord,
    VectorStyle? style,
  }) {
    final trafo = [rect[2], 0.0, 0.0, rect[3], rect[0], rect[1]];
    return VectorCircle(
      trafo: trafo,
      initialTrafo: List.of(trafo),
      angle1: angle1,
      angle2: angle2,
      arcType: arcType,
      style: style,
    );
  }

  Offset get center => const Offset(0.5, 0.5);

  @override
  List<VectorPath> getInitialPaths() {
    return _getCirclePaths(angle1, angle2, arcType);
  }

  @override
  DocumentObject createEmpty() => VectorCircle();

  @override
  void copyFields(DocumentObject target) {
    super.copyFields(target);
    if (target is VectorCircle) {
      target.angle1 = angle1;
      target.angle2 = angle2;
      target.arcType = arcType;
      target.initialTrafo = List.of(initialTrafo);
    }
  }

  @override
  String toString() =>
      'VectorCircle(angle1=${angle1.toStringAsFixed(2)}, angle2=${angle2.toStringAsFixed(2)}, $arcType)';
}

// ---------------------------------------------------------------------------
// Polygon / Star
// ---------------------------------------------------------------------------

/// A regular polygon or star shape.
///
/// The initial shape is inscribed in a unit circle centered at (0.5, 0.5).
class VectorPolygon extends PrimitiveObject {
  VectorPolygon({
    super.parent,
    super.trafo,
    super.style,
    super.fillTrafo,
    super.strokeTrafo,
    this.cornersNum = kDefaultPolygonNum,
    this.angle1 = 0.0,
    this.angle2 = 0.0,
    this.coef1 = 1.0,
    this.coef2 = 1.0,
    List<double>? initialTrafo,
  }) : initialTrafo = initialTrafo ?? List.of(kNormalTrafo);

  /// Number of corners.
  int cornersNum;

  /// Angle offset for corners (radians).
  double angle1;

  /// Angle offset for midpoints (radians).
  double angle2;

  /// Radius coefficient for corners (1.0 = on the circle).
  double coef1;

  /// Radius coefficient for midpoints (1.0 = on the circle; <1 = star).
  double coef2;

  /// Initial transform.
  List<double> initialTrafo;

  @override
  bool get isPolygon => true;

  @override
  bool get isClosed => true;

  double get cornerRadius => 0.5;

  double get midpointRadius => cornerRadius * math.cos(math.pi / cornersNum);

  double getCornerAngle(int index) {
    var val = 2.0 * math.pi / cornersNum * index + math.pi / 2.0;
    if (val > 2.0 * math.pi) val -= 2.0 * math.pi;
    return val;
  }

  double getMidpointAngle(int index) {
    var val = getCornerAngle(index) + math.pi / cornersNum;
    if (val > 2.0 * math.pi) val -= 2.0 * math.pi;
    return val;
  }

  @override
  List<VectorPath> getInitialPaths() {
    return _getPolygonPaths(cornersNum, angle1, angle2, coef1, coef2);
  }

  @override
  DocumentObject createEmpty() => VectorPolygon();

  @override
  void copyFields(DocumentObject target) {
    super.copyFields(target);
    if (target is VectorPolygon) {
      target.cornersNum = cornersNum;
      target.angle1 = angle1;
      target.angle2 = angle2;
      target.coef1 = coef1;
      target.coef2 = coef2;
      target.initialTrafo = List.of(initialTrafo);
    }
  }

  @override
  String toString() =>
      'VectorPolygon($cornersNum corners, coef1=$coef1, coef2=$coef2)';
}

// ---------------------------------------------------------------------------
// Curve (free-form Bézier paths)
// ---------------------------------------------------------------------------

/// A free-form curve object, represented as a list of [VectorPath]s.
///
/// This is the most general primitive: rectangles, circles, and polygons can
/// all be converted to curves via [toCurve].
class VectorCurve extends PrimitiveObject {
  VectorCurve({
    super.parent,
    super.trafo,
    super.style,
    super.fillTrafo,
    super.strokeTrafo,
    List<VectorPath>? paths,
  }) : paths = paths ?? [];

  /// The sub-paths that make up this curve.
  List<VectorPath> paths;

  @override
  bool get isCurve => true;

  @override
  bool get isClosed {
    for (final path in paths) {
      if (path.isClosed) return true;
    }
    return false;
  }

  /// Whether all sub-paths are closed.
  bool get isClosedAll {
    for (final path in paths) {
      if (path.isOpen) return false;
    }
    return true;
  }

  @override
  List<VectorPath> getInitialPaths() => paths;

  @override
  DocumentObject? toCurve() => this;

  @override
  DocumentObject createEmpty() => VectorCurve();

  @override
  void copyFields(DocumentObject target) {
    super.copyFields(target);
    if (target is VectorCurve) {
      target.paths = paths.map((p) => p.copyWith()).toList();
    }
  }

  @override
  String toString() => 'VectorCurve(${paths.length} paths, closed=$isClosed)';
}

// ---------------------------------------------------------------------------
// Text
// ---------------------------------------------------------------------------

/// Artistic or paragraph text.
///
/// Text content is stored as a plain string in [textContent]. The [width]
/// field controls the text mode: -1 = artistic (single-line/free), positive
/// values define a text block width for paragraph mode.
class VectorText extends PrimitiveObject {
  VectorText({
    super.parent,
    super.trafo,
    super.style,
    super.fillTrafo,
    super.strokeTrafo,
    this.textContent = '',
    this.width = kTextBlockWidth,
    List<double>? initialTrafo,
    this.markup = const [],
  }) : initialTrafo = initialTrafo ?? List.of(kNormalTrafo);

  /// The text content.
  String textContent;

  /// Text block width (-1 = artistic mode).
  double width;

  /// Initial transform.
  List<double> initialTrafo;

  /// Rich-text markup segments.
  List<TextMarkup> markup;

  @override
  bool get isText => true;

  @override
  bool get isClosed => true;

  /// True if this is an artistic text (single-line, free placement).
  bool get isArtisticText => width == kTextBlockWidth;

  /// True if this is a paragraph text block.
  bool get isParagraphText => width > 0;

  @override
  List<VectorPath> getInitialPaths() {
    // Text path generation requires a font engine. Return an empty list
    // as a placeholder; the renderer handles text separately.
    return [];
  }

  /// The ink extent of this text, in the object's own units, measured by
  /// whoever owns the fonts.
  ///
  /// Installed by the vector editor (see `vector_editor/text_metrics.dart`),
  /// because this layer has no font engine and must not grow one: a document
  /// model that depended on a rasterizer could not be loaded, converted or
  /// serialized without one.
  ///
  /// Null falls back to [approximateInk], which is a plausible box rather than
  /// a correct one - good enough that a document opened headless still has
  /// selectable text, not good enough to place a caret with.
  static VectorTextInk Function(VectorText text)? inkProvider;

  /// The ink box of this text, measured or approximated.
  VectorTextInk get ink => inkProvider?.call(this) ?? approximateInk(this);

  /// A metrics-free estimate, for when no font engine has been installed.
  ///
  /// 0.52 em per character and the usual 0.8/0.2 split of the em box: those
  /// are the proportions of a Latin sans face, and they are only ever used to
  /// give the text *some* box rather than the zero-sized one that made text
  /// impossible to click at all.
  static VectorTextInk approximateInk(VectorText text) {
    final size = text.style.textStyle.fontSize;
    return VectorTextInk(
      width: text.textContent.length * size * 0.52,
      ascent: size * 0.8,
      descent: size * 0.2,
    );
  }

  /// The box the text occupies, transformed.
  ///
  /// Overridden because [PrimitiveObject.updateBbox] derives the box from
  /// `cachePaths`, and text has none - so every text object had
  /// `cacheBbox == Rect.zero` and could never be hit-tested, selected,
  /// double-clicked or enclosed by a rubber band. Nothing about the text was
  /// wrong on screen; it simply did not exist to the pointer.
  @override
  void updateBbox() {
    final metrics = ink;
    // The trafo's translation *is* the baseline origin - that is what the
    // renderer draws from - so the local box hangs off the origin: up by the
    // ascent, down by the descent, right by the advance.
    final corners = <Offset>[
      const Offset(0, 0),
      Offset(metrics.width, 0),
      Offset(0, -metrics.ascent),
      Offset(metrics.width, -metrics.ascent),
      Offset(0, metrics.descent),
      Offset(metrics.width, metrics.descent),
    ];
    var minX = double.infinity;
    var minY = double.infinity;
    var maxX = double.negativeInfinity;
    var maxY = double.negativeInfinity;
    for (final corner in corners) {
      final point = applyTrafoToPoint(corner, trafo);
      if (point.dx < minX) minX = point.dx;
      if (point.dy < minY) minY = point.dy;
      if (point.dx > maxX) maxX = point.dx;
      if (point.dy > maxY) maxY = point.dy;
    }
    cacheBbox = Rect.fromLTRB(minX, minY, maxX, maxY);
  }

  @override
  DocumentObject createEmpty() => VectorText();

  @override
  void copyFields(DocumentObject target) {
    super.copyFields(target);
    if (target is VectorText) {
      target.textContent = textContent;
      target.width = width;
      target.initialTrafo = List.of(initialTrafo);
      target.markup = markup.map((m) => m.copyWith()).toList();
    }
  }

  @override
  String toString() {
    final preview = textContent.length > 30
        ? '${textContent.substring(0, 30)}...'
        : textContent;
    return 'VectorText("$preview", ${isArtisticText ? "artistic" : "paragraph"})';
  }
}

/// A segment of rich-text markup applied to a range of the text.
class TextMarkup {
  const TextMarkup({
    this.startIndex = 0,
    this.endIndex = 0,
    this.fontFamily,
    this.fontSize,
    this.bold,
    this.italic,
    this.color,
  });

  final int startIndex;
  final int endIndex;
  final String? fontFamily;
  final double? fontSize;
  final bool? bold;
  final bool? italic;
  final int? color; // packed ARGB

  TextMarkup copyWith({
    int? startIndex,
    int? endIndex,
    String? fontFamily,
    double? fontSize,
    bool? bold,
    bool? italic,
    int? color,
  }) =>
      TextMarkup(
        startIndex: startIndex ?? this.startIndex,
        endIndex: endIndex ?? this.endIndex,
        fontFamily: fontFamily ?? this.fontFamily,
        fontSize: fontSize ?? this.fontSize,
        bold: bold ?? this.bold,
        italic: italic ?? this.italic,
        color: color ?? this.color,
      );
}

/// One line of text's ink extent, in the text object's own units.
final class VectorTextInk {
  const VectorTextInk({
    required this.width,
    required this.ascent,
    required this.descent,
  });

  /// The advance width of the whole string.
  final double width;

  /// How far the tallest glyph rises above the baseline.
  final double ascent;

  /// How far the deepest glyph falls below it.
  final double descent;

  double get height => ascent + descent;

  @override
  String toString() =>
      'VectorTextInk(width: $width, ascent: $ascent, descent: $descent)';
}

// ===========================================================================
// Path generators (internal)
// ===========================================================================

/// The kappa constant for approximating quarter-circles with cubic Béziers.
/// Error is ~0.027% of the radius.
const double _kappa = 0.5522847498;

/// Generates rectangle paths with optional rounded corners.
List<VectorPath> _getRectPaths(
    double x, double y, double w, double h, List<double> corners) {
  final hasRounding = corners.any((c) => c > 0.0);

  if (!hasRounding) {
    // Simple rectangle: 4 line segments, closed.
    return [
      VectorPath(
        start: Offset(x, y),
        points: [
          Offset(x, y + h),
          Offset(x + w, y + h),
          Offset(x + w, y),
        ],
        closure: PathClosure.closed,
      ),
    ];
  }

  // Rounded rectangle: approximate each corner arc with a cubic Bézier.
  final r = math.min(w, h) / 2.0;
  final c0 = corners[0].clamp(0.0, 1.0) * r; // lower-left
  final c1 = corners[1].clamp(0.0, 1.0) * r; // upper-left
  final c2 = corners[2].clamp(0.0, 1.0) * r; // upper-right
  final c3 = corners[3].clamp(0.0, 1.0) * r; // lower-right

  final points = <Object>[];

  // Start at lower-left, after the corner arc
  final start = Offset(x, y + c0);

  // Left edge → upper-left corner
  if (c1 > 0) {
    points.add(Offset(x, y + h - c1));
    points.add(CurvePoint(
      Offset(x, y + h - c1 + c1 * _kappa),
      Offset(x + c1 - c1 * _kappa, y + h),
      Offset(x + c1, y + h),
      NodeType.smooth,
    ));
  } else {
    points.add(Offset(x, y + h));
  }

  // Top edge → upper-right corner
  if (c2 > 0) {
    points.add(Offset(x + w - c2, y + h));
    points.add(CurvePoint(
      Offset(x + w - c2 + c2 * _kappa, y + h),
      Offset(x + w, y + h - c2 + c2 * _kappa),
      Offset(x + w, y + h - c2),
      NodeType.smooth,
    ));
  } else {
    points.add(Offset(x + w, y + h));
  }

  // Right edge → lower-right corner
  if (c3 > 0) {
    points.add(Offset(x + w, y + c3));
    points.add(CurvePoint(
      Offset(x + w, y + c3 - c3 * _kappa),
      Offset(x + w - c3 + c3 * _kappa, y),
      Offset(x + w - c3, y),
      NodeType.smooth,
    ));
  } else {
    points.add(Offset(x + w, y));
  }

  // Bottom edge → lower-left corner (back to start)
  if (c0 > 0) {
    points.add(Offset(x + c0, y));
    points.add(CurvePoint(
      Offset(x + c0 - c0 * _kappa, y),
      Offset(x, y + c0 - c0 * _kappa),
      Offset(x, y + c0),
      NodeType.smooth,
    ));
  } else {
    // Will close to start automatically.
  }

  return [
    VectorPath(start: start, points: points, closure: PathClosure.closed),
  ];
}

/// Generates circle/ellipse paths (unit circle centered at 0.5, 0.5).
List<VectorPath> _getCirclePaths(
    double angle1, double angle2, ArcType arcType) {
  // Full circle (angle1 == angle2 == 0)
  if (angle1 == 0 && angle2 == 0) {
    // Four quarter-circle arcs using cubic Bézier approximation.
    const cx = 0.5;
    const cy = 0.5;
    const r = 0.5;
    const k = r * _kappa;

    return [
      VectorPath(
        start: const Offset(cx + r, cy),
        points: [
          const CurvePoint(
            Offset(cx + r, cy + k),
            Offset(cx + k, cy + r),
            Offset(cx, cy + r),
            NodeType.smooth,
          ),
          const CurvePoint(
            Offset(cx - k, cy + r),
            Offset(cx - r, cy + k),
            Offset(cx - r, cy),
            NodeType.smooth,
          ),
          const CurvePoint(
            Offset(cx - r, cy - k),
            Offset(cx - k, cy - r),
            Offset(cx, cy - r),
            NodeType.smooth,
          ),
          const CurvePoint(
            Offset(cx + k, cy - r),
            Offset(cx + r, cy - k),
            Offset(cx + r, cy),
            NodeType.smooth,
          ),
        ],
        closure: PathClosure.closed,
      ),
    ];
  }

  // Arc / sector / chord
  const cx = 0.5;
  const cy = 0.5;
  const r = 0.5;

  // Generate arc points
  final points = <Object>[];
  final startAngle = angle1;
  var endAngle = angle2;
  if (endAngle <= startAngle) endAngle += 2 * math.pi;

  final startPt = Offset(
    cx + r * math.cos(startAngle),
    cy + r * math.sin(startAngle),
  );

  // Subdivide the arc into at most 90° segments
  var currentAngle = startAngle;
  while (currentAngle < endAngle) {
    var segEnd = currentAngle + math.pi / 2.0;
    if (segEnd > endAngle) segEnd = endAngle;
    final segSpan = segEnd - currentAngle;
    final alpha = 4.0 / 3.0 * math.tan(segSpan / 4.0);

    final p1 = Offset(
      cx + r * math.cos(currentAngle),
      cy + r * math.sin(currentAngle),
    );
    final p4 = Offset(
      cx + r * math.cos(segEnd),
      cy + r * math.sin(segEnd),
    );
    final p2 = Offset(
      p1.dx - alpha * r * math.sin(currentAngle),
      p1.dy + alpha * r * math.cos(currentAngle),
    );
    final p3 = Offset(
      p4.dx + alpha * r * math.sin(segEnd),
      p4.dy - alpha * r * math.cos(segEnd),
    );

    points.add(CurvePoint(p2, p3, p4, NodeType.smooth));
    currentAngle = segEnd;
  }

  // Handle closure based on arc type
  PathClosure closure;
  switch (arcType) {
    case ArcType.arc:
      closure = PathClosure.opened;
    case ArcType.chord:
      closure = PathClosure.closed;
    case ArcType.pieslice:
      points.add(const Offset(cx, cy));
      closure = PathClosure.closed;
  }

  return [
    VectorPath(start: startPt, points: points, closure: closure),
  ];
}

/// Generates polygon / star paths.
List<VectorPath> _getPolygonPaths(
    int cornersNum, double angle1, double angle2, double coef1, double coef2) {
  const cx = 0.5;
  const cy = 0.5;
  const r = 0.5;

  final points = <Object>[];
  final startAngle = math.pi / 2.0 + angle1;
  final step = 2.0 * math.pi / cornersNum;

  // First corner
  final startPt = Offset(
    cx + r * coef1 * math.cos(startAngle),
    cy + r * coef1 * math.sin(startAngle),
  );

  for (var i = 0; i < cornersNum; i++) {
    // Midpoint
    final midAngle = startAngle + step * i + step / 2.0 + angle2;
    points.add(Offset(
      cx + r * coef2 * math.cos(midAngle),
      cy + r * coef2 * math.sin(midAngle),
    ));

    // Next corner (skip first since it's the start point)
    if (i < cornersNum - 1) {
      final cornerAngle = startAngle + step * (i + 1) + angle1;
      points.add(Offset(
        cx + r * coef1 * math.cos(cornerAngle),
        cy + r * coef1 * math.sin(cornerAngle),
      ));
    }
  }

  return [
    VectorPath(start: startPt, points: points, closure: PathClosure.closed),
  ];
}
