// libwayland-client.so.0 + libc bindings for POC-09.
//
// Wayland's protocol API uses inline functions generated by the protocol
// scanner (e.g. `wl_display_get_registry`, `wl_compositor_create_surface`).
// Those inlines live in the protocol header, not in the shared library, so
// they are NOT exported by `libwayland-client.so.0`. Calling `lookupFunction`
// on them, as we initially did, fails at runtime:
//
//     undefined symbol: wl_display_get_registry
//
// To stay 100% in Dart we reimplement the inlines by calling the exported
// runtime primitives `wl_proxy_marshal` and `wl_proxy_marshal_constructor`
// directly with the right opcode and `wl_interface` struct pointers.
// `wl_proxy_destroy` (also exported) handles proxy teardown.
// ignore_for_file: non_constant_identifier_names

import 'dart:ffi';

import 'package:ffi/ffi.dart';

// --- libwayland-client -----------------------------------------------------

final DynamicLibrary libWayland = DynamicLibrary.open('libwayland-client.so.0');

// ---- truly exported Wayland functions ------------------------------------

// wl_display_connect(const char *name)
typedef WlDisplayConnectNative = Pointer<Void> Function(Pointer<Utf8> name);
typedef WlDisplayConnectDart = Pointer<Void> Function(Pointer<Utf8> name);
final WlDisplayConnectDart wl_display_connect =
    libWayland.lookupFunction<WlDisplayConnectNative, WlDisplayConnectDart>(
        'wl_display_connect');

// wl_display_disconnect(struct wl_display *display)
typedef WlDisplayDisconnectNative = Void Function(Pointer<Void> display);
typedef WlDisplayDisconnectDart = void Function(Pointer<Void> display);
final WlDisplayDisconnectDart wl_display_disconnect = libWayland.lookupFunction<
    WlDisplayDisconnectNative,
    WlDisplayDisconnectDart>('wl_display_disconnect');

// int wl_display_roundtrip(struct wl_display *display)
typedef WlDisplayRoundtripNative = Int32 Function(Pointer<Void> display);
typedef WlDisplayRoundtripDart = int Function(Pointer<Void> display);
final WlDisplayRoundtripDart wl_display_roundtrip =
    libWayland.lookupFunction<WlDisplayRoundtripNative, WlDisplayRoundtripDart>(
        'wl_display_roundtrip');

// int wl_display_dispatch(struct wl_display *display)
typedef WlDisplayDispatchNative = Int32 Function(Pointer<Void> display);
typedef WlDisplayDispatchDart = int Function(Pointer<Void> display);
final WlDisplayDispatchDart wl_display_dispatch =
    libWayland.lookupFunction<WlDisplayDispatchNative, WlDisplayDispatchDart>(
        'wl_display_dispatch');

// int wl_display_flush(struct wl_display *display)
typedef WlDisplayFlushNative = Int32 Function(Pointer<Void> display);
typedef WlDisplayFlushDart = int Function(Pointer<Void> display);
final WlDisplayFlushDart wl_display_flush =
    libWayland.lookupFunction<WlDisplayFlushNative, WlDisplayFlushDart>(
        'wl_display_flush');

// int wl_proxy_add_listener(struct wl_proxy *proxy,
//                           void (**implementation)(void), void *data);
// NOTE: `wl_registry_add_listener` is NOT exported by the shared library —
// the scanner generates it as an inline around this primitive — so it is
// reimplemented in Dart below, like the other inlines.
typedef WlProxyAddListenerNative = Int32 Function(
    Pointer<Void> proxy, Pointer<Void> implementation, Pointer<Void> data);
typedef WlProxyAddListenerDart = int Function(
    Pointer<Void> proxy, Pointer<Void> implementation, Pointer<Void> data);
final WlProxyAddListenerDart wl_proxy_add_listener =
    libWayland.lookupFunction<WlProxyAddListenerNative, WlProxyAddListenerDart>(
        'wl_proxy_add_listener');

// struct wl_interface { const char *name; int version;
//                        uint32_t method_count; ... };
// Only the `name` field (offset 0) is ever dereferenced, by the
// `wl_registry_bind` inline reimplementation below. The exported
// `wl_*_interface` symbols point at instances of this struct.
final class WlInterface extends Struct {
  external Pointer<Utf8> name;
  @Int32()
  external int version;
  @Uint32()
  external int method_count;
  external Pointer<Void> methods;
  @Uint32()
  external int event_count;
  external Pointer<Void> events;
}

// struct wl_proxy *wl_proxy_marshal_constructor_versioned(
//     struct wl_proxy *proxy, uint32_t opcode,
//     const struct wl_interface *interface, uint32_t version, ...);
// Fixed-shape signature matching the `wl_registry_bind` call site: the
// variadic args are `name:uint`, `interface->name:const char*`,
// `version:uint`, NULL. NOTE: `wl_registry_bind` itself is NOT exported —
// the scanner generates it as an inline around this primitive — so it is
// reimplemented in Dart below, like the other inlines.
typedef WlProxyMarshalConstructorVersionedBindNative = Pointer<Void> Function(
    Pointer<Void> proxy,
    Uint32 opcode,
    Pointer<Void> interface,
    Uint32 version,
    Uint32 name,
    Pointer<Utf8> interfaceName,
    Uint32 requestVersion,
    Pointer<Void> sentinel);
typedef WlProxyMarshalConstructorVersionedBindDart = Pointer<Void> Function(
    Pointer<Void> proxy,
    int opcode,
    Pointer<Void> interface,
    int version,
    int name,
    Pointer<Utf8> interfaceName,
    int requestVersion,
    Pointer<Void> sentinel);
final WlProxyMarshalConstructorVersionedBindDart
    wl_proxy_marshal_constructor_versioned_bind = libWayland.lookupFunction<
            WlProxyMarshalConstructorVersionedBindNative,
            WlProxyMarshalConstructorVersionedBindDart>(
        'wl_proxy_marshal_constructor_versioned');

// ---- wl_proxy_* runtime primitives (replace the inline-generated
//      protocol functions from the scanner). ------------------------------

// void wl_proxy_destroy(struct wl_proxy *proxy);
typedef WlProxyDestroyNative = Void Function(Pointer<Void> proxy);
typedef WlProxyDestroyDart = void Function(Pointer<Void> proxy);
final WlProxyDestroyDart wl_proxy_destroy =
    libWayland.lookupFunction<WlProxyDestroyNative, WlProxyDestroyDart>(
        'wl_proxy_destroy');

// Variadic marshalling primitives. The C signatures are variadic:
//
//   void wl_proxy_marshal(struct wl_proxy *proxy, uint32_t opcode, ...);
//   struct wl_proxy *wl_proxy_marshal_constructor(
//       struct wl_proxy *proxy, uint32_t opcode,
//       const struct wl_interface *interface, ...);
//
// Dart's `lookupFunction` cannot declare a variadic ABI directly, but we
// can declare a fixed-shape signature that matches the **call site we
// actually need** for each opcode. The C ABI passes the trailing variadic
// arguments as regular GP registers / stack slots, so a fixed signature is
// valid as long as we always terminate with a NULL sentinel (which the
// scanner-generated inlines do too).

// wl_proxy_marshal(proxy, opcode, NULL) — terminator-only variants used by
// `wl_surface_commit` (opcode 6), `wl_surface_destroy` (opcode 0),
// `wl_shm_pool_destroy` (opcode 1), `wl_compositor_release` (opcode 2).
typedef WlProxyMarshal0Native = Void Function(
    Pointer<Void> proxy, Uint32 opcode, Pointer<Void> sentinel);
typedef WlProxyMarshal0Dart = void Function(
    Pointer<Void> proxy, int opcode, Pointer<Void> sentinel);
final WlProxyMarshal0Dart wl_proxy_marshal_0 =
    libWayland.lookupFunction<WlProxyMarshal0Native, WlProxyMarshal0Dart>(
        'wl_proxy_marshal');

// wl_proxy_marshal(proxy, opcode, buffer, x, y, NULL) — `wl_surface_attach`.
typedef WlProxyMarshal3Native = Void Function(
    Pointer<Void> proxy,
    Uint32 opcode,
    Pointer<Void> buffer,
    Int32 x,
    Int32 y,
    Pointer<Void> sentinel);
typedef WlProxyMarshal3Dart = void Function(Pointer<Void> proxy, int opcode,
    Pointer<Void> buffer, int x, int y, Pointer<Void> sentinel);
final WlProxyMarshal3Dart wl_proxy_marshal_3 =
    libWayland.lookupFunction<WlProxyMarshal3Native, WlProxyMarshal3Dart>(
        'wl_proxy_marshal');

// wl_proxy_marshal(proxy, opcode, x, y, width, height, NULL) — `wl_surface_damage`.
typedef WlProxyMarshal5Native = Void Function(
    Pointer<Void> proxy,
    Uint32 opcode,
    Int32 x,
    Int32 y,
    Int32 width,
    Int32 height,
    Pointer<Void> sentinel);
typedef WlProxyMarshal5Dart = void Function(Pointer<Void> proxy, int opcode,
    int x, int y, int width, int height, Pointer<Void> sentinel);
final WlProxyMarshal5Dart wl_proxy_marshal_5 =
    libWayland.lookupFunction<WlProxyMarshal5Native, WlProxyMarshal5Dart>(
        'wl_proxy_marshal');

// wl_proxy_marshal_constructor(proxy, opcode, interface, NULL) — variants
// used by `wl_display_get_registry` (opcode 1) and
// `wl_compositor_create_surface` (opcode 0). Both take only the interface
// pointer plus terminator.
typedef WlProxyMarshalConstructorIface0Native = Pointer<Void> Function(
    Pointer<Void> proxy,
    Uint32 opcode,
    Pointer<Void> interface,
    Pointer<Void> sentinel);
typedef WlProxyMarshalConstructorIface0Dart = Pointer<Void> Function(
    Pointer<Void> proxy,
    int opcode,
    Pointer<Void> interface,
    Pointer<Void> sentinel);
final WlProxyMarshalConstructorIface0Dart wl_proxy_marshal_constructor_iface0 =
    libWayland.lookupFunction<WlProxyMarshalConstructorIface0Native,
        WlProxyMarshalConstructorIface0Dart>('wl_proxy_marshal_constructor');

// wl_proxy_marshal_constructor(proxy, opcode, interface, fd, size, NULL) —
// `wl_shm_create_pool` (opcode 0) takes `fd:int` and `size:int`.
typedef WlProxyMarshalConstructorIface2IntNative = Pointer<Void> Function(
    Pointer<Void> proxy,
    Uint32 opcode,
    Pointer<Void> interface,
    Int32 fd,
    Int32 size,
    Pointer<Void> sentinel);
typedef WlProxyMarshalConstructorIface2IntDart = Pointer<Void> Function(
    Pointer<Void> proxy,
    int opcode,
    Pointer<Void> interface,
    int fd,
    int size,
    Pointer<Void> sentinel);
final WlProxyMarshalConstructorIface2IntDart
    wl_proxy_marshal_constructor_iface2_int = libWayland.lookupFunction<
        WlProxyMarshalConstructorIface2IntNative,
        WlProxyMarshalConstructorIface2IntDart>('wl_proxy_marshal_constructor');

// wl_proxy_marshal_constructor(proxy, opcode, interface, offset, width,
//                              height, stride, format, NULL) —
// `wl_shm_pool_create_buffer` (opcode 0).
typedef WlProxyMarshalConstructorIface5IntNative = Pointer<Void> Function(
    Pointer<Void> proxy,
    Uint32 opcode,
    Pointer<Void> interface,
    Int32 offset,
    Int32 width,
    Int32 height,
    Int32 stride,
    Uint32 format,
    Pointer<Void> sentinel);
typedef WlProxyMarshalConstructorIface5IntDart = Pointer<Void> Function(
    Pointer<Void> proxy,
    int opcode,
    Pointer<Void> interface,
    int offset,
    int width,
    int height,
    int stride,
    int format,
    Pointer<Void> sentinel);
final WlProxyMarshalConstructorIface5IntDart
    wl_proxy_marshal_constructor_iface5_int = libWayland.lookupFunction<
        WlProxyMarshalConstructorIface5IntNative,
        WlProxyMarshalConstructorIface5IntDart>('wl_proxy_marshal_constructor');

// ---- Dart reimplementations of the scanner inlines ----------------------
//
// Each function below mirrors the inline that the wayland scanner emits in
// `wayland-client-protocol.h`. The opcode numbers come from the `wayland.xml`
// protocol spec (see https://wayland.freedesktop.org/docs/html/apa.html).

// Opcodes from the wayland protocol XML (kept here so the inline
// reimplementations have a single source of truth).
const int wlDisplayGetRegistryOpcode = 1;
const int wlRegistryBindOpcode = 0;
const int wlCompositorCreateSurfaceOpcode = 0;
const int wlShmCreatePoolOpcode = 0;
const int wlShmPoolCreateBufferOpcode = 0;
const int wlShmPoolDestroyOpcode = 1;
const int wlSurfaceAttachOpcode = 1;
const int wlSurfaceDamageOpcode = 2;
const int wlSurfaceCommitOpcode = 6;
const int wlSurfaceDestroyOpcode = 0;
const int wlBufferDestroyOpcode = 0;

/// Reimplements `wl_display_get_registry(struct wl_display *display)`.
Pointer<Void> wl_display_get_registry(Pointer<Void> display) {
  return wl_proxy_marshal_constructor_iface0(
      display, wlDisplayGetRegistryOpcode, wl_registry_interface_ptr, nullptr);
}

/// Reimplements `wl_registry_bind(struct wl_registry *, uint32_t name,
/// const struct wl_interface *interface, uint32_t version)`. The generated
/// inline marshals `name`, `interface->name` (a string) and `version` via
/// `wl_proxy_marshal_constructor_versioned`, passing `version` both as the
/// constructor version and as the request argument.
Pointer<Void> wl_registry_bind(
    Pointer<Void> registry, int name, Pointer<Void> interface, int version) {
  return wl_proxy_marshal_constructor_versioned_bind(
      registry,
      wlRegistryBindOpcode,
      interface,
      version,
      name,
      interface.cast<WlInterface>().ref.name,
      version,
      nullptr);
}

/// Reimplements `wl_compositor_create_surface(struct wl_compositor *compositor)`.
Pointer<Void> wl_compositor_create_surface(Pointer<Void> compositor) {
  return wl_proxy_marshal_constructor_iface0(compositor,
      wlCompositorCreateSurfaceOpcode, wl_surface_interface_ptr, nullptr);
}

/// Reimplements `wl_shm_create_pool(struct wl_shm *wl_shm, int fd, int size)`.
Pointer<Void> wl_shm_create_pool(Pointer<Void> shm, int fd, int size) {
  return wl_proxy_marshal_constructor_iface2_int(
      shm, wlShmCreatePoolOpcode, wl_shm_pool_interface_ptr, fd, size, nullptr);
}

/// Reimplements `wl_shm_pool_create_buffer(struct wl_shm_pool *pool,
/// int offset, int width, int height, int stride, uint format)`.
Pointer<Void> wl_shm_pool_create_buffer(Pointer<Void> pool, int offset,
    int width, int height, int stride, int format) {
  return wl_proxy_marshal_constructor_iface5_int(
      pool,
      wlShmPoolCreateBufferOpcode,
      wl_buffer_interface_ptr,
      offset,
      width,
      height,
      stride,
      format,
      nullptr);
}

/// Reimplements `wl_surface_attach(struct wl_surface *, struct wl_buffer *, int, int)`.
void wl_surface_attach(
    Pointer<Void> surface, Pointer<Void> buffer, int x, int y) {
  wl_proxy_marshal_3(surface, wlSurfaceAttachOpcode, buffer, x, y, nullptr);
}

/// Reimplements `wl_surface_damage(struct wl_surface *, int, int, int, int)`.
void wl_surface_damage(
    Pointer<Void> surface, int x, int y, int width, int height) {
  wl_proxy_marshal_5(
      surface, wlSurfaceDamageOpcode, x, y, width, height, nullptr);
}

/// Reimplements `wl_surface_commit(struct wl_surface *)`.
void wl_surface_commit(Pointer<Void> surface) {
  wl_proxy_marshal_0(surface, wlSurfaceCommitOpcode, nullptr);
}

/// Reimplements `wl_surface_destroy(struct wl_surface *)`.
void wl_surface_destroy(Pointer<Void> surface) {
  wl_proxy_marshal_0(surface, wlSurfaceDestroyOpcode, nullptr);
  wl_proxy_destroy(surface);
}

/// Reimplements `wl_shm_pool_destroy(struct wl_shm_pool *)`.
void wl_shm_pool_destroy(Pointer<Void> pool) {
  wl_proxy_marshal_0(pool, wlShmPoolDestroyOpcode, nullptr);
  wl_proxy_destroy(pool);
}

/// Reimplements `wl_buffer_destroy(struct wl_buffer *)`.
void wl_buffer_destroy(Pointer<Void> buffer) {
  wl_proxy_marshal_0(buffer, wlBufferDestroyOpcode, nullptr);
  wl_proxy_destroy(buffer);
}

/// Reimplements `wl_registry_destroy(struct wl_registry *)`.
void wl_registry_destroy(Pointer<Void> registry) {
  // `wl_registry::destroy` (opcode 1) is a destructor added in version 1 of
  // the registry interface. Marshalling the opcode is safe even when the
  // compositor advertises an older version because the request is logically
  // an immediate disconnect; if the server rejects it the proxy is still
  // torn down locally by `wl_proxy_destroy` below.
  wl_proxy_marshal_0(registry, 1, nullptr);
  wl_proxy_destroy(registry);
}

/// Convenience wrapper for proxies whose interface has no destructor opcode
/// (e.g. `wl_compositor`/`wl_shm` bound at version 1, where `release` was
/// only added in version 4 / version 2 respectively).
void wl_proxy_destroy_only(Pointer<Void> proxy) {
  wl_proxy_destroy(proxy);
}

/// Reimplements `wl_registry_add_listener(struct wl_registry *,
/// const struct wl_registry_listener *, void *)`.
int wl_registry_add_listener(
    Pointer<Void> registry, Pointer<Void> listener, Pointer<Void> data) {
  return wl_proxy_add_listener(registry, listener, data);
}

// --- Listener struct ------------------------------------------------------

// struct wl_registry_listener {
//     void (*global)(void *data, struct wl_registry *, uint32_t name,
//                    const char *interface, uint32_t version);
//     void (*global_remove)(void *data, struct wl_registry *, uint32_t name);
// };
typedef WlRegistryGlobalNative = Void Function(
    Pointer<Void> data,
    Pointer<Void> registry,
    Uint32 name,
    Pointer<Utf8> interface,
    Uint32 version);
typedef WlRegistryGlobalRemoveNative = Void Function(
    Pointer<Void> data, Pointer<Void> registry, Uint32 name);

final class WlRegistryListener extends Struct {
  external Pointer<NativeFunction<WlRegistryGlobalNative>> global;
  external Pointer<NativeFunction<WlRegistryGlobalRemoveNative>> global_remove;
}

// --- libc (Linux only) ------------------------------------------------------

final DynamicLibrary libc = DynamicLibrary.open('libc.so.6');

// int memfd_create(const char *name, unsigned int flags);
typedef MemfdCreateNative = Int32 Function(Pointer<Utf8> name, Uint32 flags);
typedef MemfdCreateDart = int Function(Pointer<Utf8> name, int flags);
final MemfdCreateDart memfd_create =
    libc.lookupFunction<MemfdCreateNative, MemfdCreateDart>('memfd_create');

// int ftruncate(int fd, off_t length);
typedef FtruncateNative = Int32 Function(Int32 fd, Long length);
typedef FtruncateDart = int Function(int fd, int length);
final FtruncateDart ftruncate =
    libc.lookupFunction<FtruncateNative, FtruncateDart>('ftruncate');

// void *mmap(void *addr, size_t length, int prot, int flags, int fd, off_t offset);
typedef MmapNative = Pointer<Void> Function(Pointer<Void> addr, IntPtr length,
    Int32 prot, Int32 flags, Int32 fd, Long offset);
typedef MmapDart = Pointer<Void> Function(
    Pointer<Void> addr, int length, int prot, int flags, int fd, int offset);
final MmapDart mmap = libc.lookupFunction<MmapNative, MmapDart>('mmap');

// int munmap(void *addr, size_t length);
typedef MunmapNative = Int32 Function(Pointer<Void> addr, IntPtr length);
typedef MunmapDart = int Function(Pointer<Void> addr, int length);
final MunmapDart munmap =
    libc.lookupFunction<MunmapNative, MunmapDart>('munmap');

// int close(int fd);
typedef CloseNative = Int32 Function(Int32 fd);
typedef CloseDart = int Function(int fd);
final CloseDart close_fd = libc.lookupFunction<CloseNative, CloseDart>('close');

// --- Constants -------------------------------------------------------------

// MFD_CLOEXEC = 1 (linux/memfd.h).
const int mfdCloexec = 1;

// PROT_* / MAP_* constants from <sys/mman.h>.
const int protRead = 1;
const int protWrite = 2;
const int mapShared = 1;

// Sentinel value used by mmap to indicate failure (`MAP_FAILED == (void*)-1`).
final Pointer<Void> mapFailed = Pointer.fromAddress(-1);

// Wayland wl_shm::format canonical values (see
// https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_shm-enum-format).
const int wlShmFormatArgb8888 = 0;
const int wlShmFormatXrgb8888 = 1;

// Opaque `wl_interface` struct pointers exported from libwayland-client. We
// never dereference them: they are passed straight into `wl_registry_bind` and
// the `wl_proxy_marshal_constructor*` calls. The pointer values are resolved
// lazily on first access via getters so that the bindings file can be loaded
// on platforms without libwayland (e.g. Windows) without throwing.
Pointer<Void>? _wl_registry_interface_ptr;
Pointer<Void>? _wl_surface_interface_ptr;
Pointer<Void>? _wl_shm_interface_ptr;
Pointer<Void>? _wl_shm_pool_interface_ptr;
Pointer<Void>? _wl_buffer_interface_ptr;
Pointer<Void>? _wl_compositor_interface_ptr;

Pointer<Void> get wl_registry_interface_ptr {
  _wl_registry_interface_ptr ??=
      libWayland.lookup<Void>('wl_registry_interface');
  return _wl_registry_interface_ptr!;
}

Pointer<Void> get wl_surface_interface_ptr {
  _wl_surface_interface_ptr ??= libWayland.lookup<Void>('wl_surface_interface');
  return _wl_surface_interface_ptr!;
}

Pointer<Void> get wl_shm_interface_ptr {
  _wl_shm_interface_ptr ??= libWayland.lookup<Void>('wl_shm_interface');
  return _wl_shm_interface_ptr!;
}

Pointer<Void> get wl_shm_pool_interface_ptr {
  _wl_shm_pool_interface_ptr ??=
      libWayland.lookup<Void>('wl_shm_pool_interface');
  return _wl_shm_pool_interface_ptr!;
}

Pointer<Void> get wl_buffer_interface_ptr {
  _wl_buffer_interface_ptr ??= libWayland.lookup<Void>('wl_buffer_interface');
  return _wl_buffer_interface_ptr!;
}

Pointer<Void> get wl_compositor_interface_ptr {
  _wl_compositor_interface_ptr ??=
      libWayland.lookup<Void>('wl_compositor_interface');
  return _wl_compositor_interface_ptr!;
}
