/// `PcmAudioPlayers.openFile`, the path that does not decode the file first.
///
/// Everything here needs a real render endpoint, so every test is skipped when
/// the machine has none - the same rule `pcm_audio_players_test.dart` follows,
/// and these two files compete for the same device, so
/// `dart test test/audio --concurrency=1` is the first thing to try if one
/// goes flaky.
///
/// The clips played here are **silent WAVs generated by the test**, not the
/// repository's drum samples. Nothing asserted below depends on the signal -
/// every check is about format, clock, seek, end-of-stream or disposal - and a
/// suite that plays a cymbal crash through the speakers on every run is a
/// suite people stop running. Generating them also removes a dependency on an
/// example's assets and lets the duration assertions name a number this file
/// controls.
///
/// One compressed-container case is kept on the real MP3, without ever calling
/// `play()`, so the cursor path over a codec is still covered.
library;

import 'dart:io';
import 'dart:typed_data';

import 'package:dart_ui/audio.dart';
import 'package:test/test.dart';

/// Whether this machine can render audio at all.
bool _hasRenderEndpoint() {
  if (!Platform.isWindows) return false;
  try {
    final WasapiAudioBackend backend = WasapiAudioBackend();
    return backend.isAvailable && backend.enumerateDevices().isNotEmpty;
  } on Object {
    return false;
  }
}

String _sample(List<String> parts) =>
    File(parts.join(Platform.pathSeparator)).absolute.path;

/// O MP3 real, usado apenas onde nada e reproduzido.
final String _mp3 = _sample(<String>[
  'examples',
  'drumer',
  'samples',
  'AK-Mixa-Kit',
  'kick 1.mp3',
]);

/// Duracoes das fixtures silenciosas, em milissegundos.
const int _longMs = 4000;
const int _shortMs = 500;

late final Directory _fixtures;
late final String _wav;
late final String _shortWav;

/// Escreve um WAV PCM de 16 bits cheio de zeros.
///
/// O cabecalho e o de sempre; so as amostras sao silencio. O decodificador do
/// sistema percorre exatamente o mesmo caminho que percorreria com musica.
String _writeSilentWav(String path, int milliseconds) {
  const int sampleRate = 44100;
  const int channels = 2;
  const int bitsPerSample = 16;
  const int bytesPerFrame = channels * bitsPerSample ~/ 8;
  final int frames = sampleRate * milliseconds ~/ 1000;
  final int dataBytes = frames * bytesPerFrame;

  final BytesBuilder out = BytesBuilder();
  void ascii(String s) => out.add(s.codeUnits);
  void u32(int v) => out.add(<int>[
        v & 0xFF,
        (v >> 8) & 0xFF,
        (v >> 16) & 0xFF,
        (v >> 24) & 0xFF,
      ]);
  void u16(int v) => out.add(<int>[v & 0xFF, (v >> 8) & 0xFF]);

  ascii('RIFF');
  u32(36 + dataBytes);
  ascii('WAVE');
  ascii('fmt ');
  u32(16);
  u16(1); // PCM
  u16(channels);
  u32(sampleRate);
  u32(sampleRate * bytesPerFrame);
  u16(bytesPerFrame);
  u16(bitsPerSample);
  ascii('data');
  u32(dataBytes);
  out.add(Uint8List(dataBytes));

  File(path).writeAsBytesSync(out.takeBytes());
  return path;
}

/// Polls [ready] until it holds, and reports whether it did in time.
Future<bool> _waitUntil(
  bool Function() ready, {
  Duration timeout = const Duration(seconds: 8),
}) async {
  final Stopwatch elapsed = Stopwatch()..start();
  while (elapsed.elapsed < timeout) {
    if (ready()) return true;
    await Future<void>.delayed(const Duration(milliseconds: 5));
  }
  return ready();
}

void main() {
  final bool hasEndpoint = _hasRenderEndpoint();
  final Object? skip =
      hasEndpoint ? null : 'no active WASAPI render endpoint on this machine';

  setUpAll(() {
    _fixtures = Directory.systemTemp.createTempSync('dart_ui_silent_audio');
    _wav = _writeSilentWav('${_fixtures.path}/silence_long.wav', _longMs);
    _shortWav =
        _writeSilentWav('${_fixtures.path}/silence_short.wav', _shortMs);
  });

  tearDownAll(() {
    if (_fixtures.existsSync()) _fixtures.deleteSync(recursive: true);
  });

  group('PcmAudioPlayers.openFile', () {
    test('knows the format and the length before playing a sample', () async {
      final PcmAudioPlayer? player = PcmAudioPlayers.openFile(_wav);
      expect(player, isNotNull);
      addTearDown(player!.dispose);

      expect(player.sampleRate, greaterThan(0));
      expect(player.channels, greaterThan(0));
      // From the container's header, not from counting decoded frames - which
      // is the entire reason this path exists.
      expect(
        player.duration.inMilliseconds,
        closeTo(_longMs, 60),
        reason: 'the duration should come from the container',
      );
      expect(player.position, Duration.zero);
      expect(player.isRunning, isFalse);
    });

    test('lê formato e duração de um container comprimido, sem tocar', () {
      // O MP3 real, e nenhuma chamada a play(): o que se cobre aqui é o cursor
      // do leitor sobre um codec — duração vinda do container, não de contar
      // frames decodificados — e isso não exige som nenhum.
      final PcmAudioPlayer? player = PcmAudioPlayers.openFile(_mp3);
      expect(player, isNotNull);
      addTearDown(player!.dispose);

      expect(player.sampleRate, greaterThan(0));
      expect(player.channels, greaterThan(0));
      expect(player.duration, greaterThan(Duration.zero));
      expect(player.position, Duration.zero);
      expect(player.isRunning, isFalse);
    });

    test('starts playing well inside a second', () async {
      // The number that motivated the whole streaming path. It is generous
      // here - four seconds rather than the one the design targets - because
      // this is a shared CI-style assertion and the first WASAPI stream in a
      // process pays a one-off engine warm-up of around half a second that has
      // nothing to do with the file. What it is really guarding is the failure
      // mode it replaced, which was *minutes*.
      final Stopwatch elapsed = Stopwatch()..start();
      final PcmAudioPlayer player = PcmAudioPlayers.openFile(_wav)!;
      addTearDown(player.dispose);
      player.play();
      expect(
        await _waitUntil(() => player.position > Duration.zero),
        isTrue,
        reason: 'the endpoint never started consuming this file',
      );
      elapsed.stop();
      expect(elapsed.elapsed, lessThan(const Duration(seconds: 4)));
    });

    test('advances at real time, and stops when paused', () async {
      final PcmAudioPlayer player = PcmAudioPlayers.openFile(_wav)!;
      addTearDown(player.dispose);

      player.play();
      expect(player.isRunning, isTrue);
      expect(
        await _waitUntil(
          () => player.position > const Duration(milliseconds: 20),
        ),
        isTrue,
      );

      final Duration first = player.position;
      final Stopwatch wall = Stopwatch()..start();
      await Future<void>.delayed(const Duration(milliseconds: 300));
      wall.stop();
      final Duration second = player.position;
      expect(second, greaterThan(first));
      expect(
        (second - first).inMicroseconds / wall.elapsedMicroseconds,
        inInclusiveRange(0.5, 1.6),
        reason: 'a file played at the wrong rate drains at the wrong speed',
      );

      player.pause();
      expect(player.isRunning, isFalse);
      await Future<void>.delayed(const Duration(milliseconds: 120));
      final Duration paused = player.position;
      await Future<void>.delayed(const Duration(milliseconds: 150));
      expect(player.position, paused, reason: 'a paused clock must stand');

      player.play();
      expect(
        await _waitUntil(() => player.position > paused),
        isTrue,
        reason: 'the clock did not resume',
      );
    });

    test('answers a seek before the decoder has acted on it', () async {
      final PcmAudioPlayer player = PcmAudioPlayers.openFile(_wav)!;
      addTearDown(player.dispose);

      player.seek(const Duration(milliseconds: 2500));
      expect(
        player.position.inMilliseconds,
        closeTo(2500, 5),
        reason: 'a seek must be visible immediately, not one refill later',
      );

      player.play();
      expect(
        await _waitUntil(
          () => player.position > const Duration(milliseconds: 2600),
        ),
        isTrue,
        reason: 'playback did not resume at the new position',
      );
      // And it landed near where it was asked to, not back at the start: a
      // producer that failed to reposition would play from zero.
      expect(player.position, greaterThan(const Duration(milliseconds: 2400)));
      expect(player.position, lessThan(const Duration(milliseconds: 3600)));
    });

    test('clamps a seek to the declared duration', () {
      final PcmAudioPlayer player = PcmAudioPlayers.openFile(_wav)!;
      addTearDown(player.dispose);

      player.seek(const Duration(hours: 1));
      expect(player.position, player.duration);
      player.seek(const Duration(seconds: -30));
      expect(player.position, Duration.zero);
    });

    test('plays to the end and stops there', () async {
      final PcmAudioPlayer player = PcmAudioPlayers.openFile(_shortWav)!;
      addTearDown(player.dispose);

      expect(player.duration, greaterThan(Duration.zero));
      player.play();
      expect(
        await _waitUntil(() => !player.isRunning),
        isTrue,
        reason: 'playback never reached the end of the file',
      );
      // The last buffer is played, not truncated: the clock only reports the
      // end once the endpoint has drained it.
      expect(
        player.position.inMilliseconds,
        closeTo(player.duration.inMilliseconds, 60),
      );
    });

    test('a file with no audio track opens no player', () {
      expect(PcmAudioPlayers.openFile('no-such-file.mp4'), isNull);
      expect(PcmAudioPlayers.openFile('pubspec.yaml'), isNull);
      expect(PcmAudioPlayers.openFile(''), isNull);
    });

    test('disposing releases both isolates, twice over', () async {
      final PcmAudioPlayer player = PcmAudioPlayers.openFile(_wav)!;
      player.play();
      await _waitUntil(() => player.position > Duration.zero);
      await player.dispose();
      // Disposing twice is a no-op, as everything in this package promises,
      // and the second call must not double-free the ring.
      await player.dispose();
      expect(player.isRunning, isFalse);
    });

    test('several players can stream at once', () async {
      final PcmAudioPlayer first = PcmAudioPlayers.openFile(_wav)!;
      addTearDown(first.dispose);
      final PcmAudioPlayer second = PcmAudioPlayers.openFile(_shortWav)!;
      addTearDown(second.dispose);

      first.play();
      second.play();
      expect(
        await _waitUntil(
          () =>
              first.position > Duration.zero && second.position > Duration.zero,
        ),
        isTrue,
        reason: 'two streaming players should not block each other',
      );
    });
  }, skip: skip);
}
