/// The system clipboard, as a port the core can name and no backend owns.
///
/// Copy, cut and paste are the one editing feature that is not a function of
/// the document: the text has to leave this process and come back from another
/// one. That crossing is what this file models, and it models it with exactly
/// two operations - read the text, write the text - because everything else a
/// clipboard can carry (images, files, HTML, a private format) differs so much
/// between platforms that a shared contract for it would be a lie. Text is the
/// format all three targets agree on, so text is what the port promises.
///
/// ## Why every operation is asynchronous
///
/// [Clipboard.readText] returns a `Future` even though Windows can answer
/// immediately, and that is deliberate rather than defensive:
///
///  * **X11 has no clipboard.** It has *selections*, which are owned by a
///    client. Reading one means `XConvertSelection` on the owner, then waiting
///    for that client to answer with a `SelectionNotify` event carrying the
///    data on a window property - and large transfers arrive in `INCR` chunks,
///    one property change at a time. The answer therefore arrives through this
///    process's own event loop, an unknown number of round trips later, and the
///    owning client may be busy, or may exit mid-transfer and never answer at
///    all. A synchronous API could only be built by spinning a nested event
///    loop inside the caller's frame, which reenters the widget tree, or by
///    blocking the UI thread on another application's responsiveness. Both are
///    the classic X11 clipboard hang.
///  * **Wayland is the same shape** with different names: `wl_data_offer`,
///    `receive()` with a pipe file descriptor, and the data arriving as
///    readable bytes on that pipe some time later.
///  * **macOS `NSPasteboard` looks synchronous** and mostly is, but a promised
///    type is generated by the owning application on demand, so even there the
///    read can take arbitrarily long.
///  * **Win32 is genuinely synchronous** - `OpenClipboard`, `GetClipboardData`
///    - and so `Win32Clipboard` completes its futures on the spot. Being able
///    to satisfy the async contract cheaply is not a reason to make the
///    contract synchronous: shaping the port around the one platform that
///    happens to be easy would mean rewriting every caller, including the
///    keystroke handling in a text field, on the day the X11 backend lands.
///
/// So the callers - `RenderTextField` above all - are already written to claim
/// the keystroke now and apply the edit when the clipboard answers, and a
/// backend that answers instantly simply never exercises the gap.
///
/// ## Failure is a named error, never a hang and never a lie
///
/// A clipboard operation genuinely fails: on Windows the clipboard is a
/// process-global lock, and `OpenClipboard` returns 0 while another application
/// holds it - which happens routinely, because clipboard-manager utilities open
/// it on every change. The port's answer is [ClipboardException], which names
/// the operation that failed and the backend it failed in. What implementations
/// must not do is retry in a loop until the lock frees (that is the hang), or
/// swallow the failure and report "nothing on the clipboard" (that is the lie
/// which makes a user paste stale text and never learn why).
///
/// "No text on the clipboard" is *not* a failure: it is `null` from
/// [Clipboard.readText]. The empty string is a third, distinct answer - an
/// application really did copy zero characters - and a caller that treats null
/// and `''` the same is free to, while one that reports "clipboard is empty"
/// can tell them apart.
library;

/// Reading and writing the platform's text clipboard.
///
/// Implemented once per backend - `Win32Clipboard` on Windows, `FakeClipboard`
/// in headless tests - and reached from the widget tree through the
/// application, which is the only object that knows which backend is running.
///
/// **Not in this contract, deliberately, and each for a reason:**
///
///  * *Formats other than text.* Images and file lists have no portable shape;
///    see the library comment.
///  * *A change notification.* Win32 has `WM_CLIPBOARDUPDATE`, X11 has
///    `SelectionClear` on the owner and nothing at all for observers, and macOS
///    has only a polled `changeCount`. A portable "clipboard changed" event
///    would have to be a poll on two of the three, and a poll is a design
///    decision that belongs to whoever wants it, spelled out loud.
///  * *A separate `hasText`.* On X11 it costs the same round trip as reading,
///    so it would be a slower `readText() != null` that also invites the
///    check-then-read race.
abstract interface class Clipboard {
  /// The text on the clipboard, or null when it holds no text at all.
  ///
  /// Throws [ClipboardException] when the clipboard could not be consulted -
  /// which is a different answer from null and must stay different.
  Future<String?> readText();

  /// Replaces the clipboard's contents with [text].
  ///
  /// Throws [ClipboardException] when the write did not happen. A caller that
  /// gets no exception may assume the text is there; a caller that gets one
  /// must assume the previous contents survived, because on Win32 the
  /// clipboard is not emptied until the lock is held.
  Future<void> writeText(String text);
}

/// A clipboard operation that did not happen, named.
///
/// Carries the *operation* rather than only a message because the operation is
/// what a reader needs: "OpenClipboard failed" says another process holds the
/// Windows clipboard lock and the right response is to try again later, while
/// "SetClipboardData failed" says the data was rejected and trying again will
/// fail the same way.
final class ClipboardException implements Exception {
  const ClipboardException({
    required this.operation,
    required this.reason,
    this.backend,
  });

  /// The call that failed: `OpenClipboard`, `readText`, `SelectionNotify`.
  final String operation;

  /// Why, in words that name the cause rather than restate the failure.
  final String reason;

  /// Which implementation reported it, when there is one.
  final String? backend;

  @override
  String toString() => 'ClipboardException: $operation failed'
      '${backend == null ? '' : ' in $backend'} - $reason';
}

/// The clipboard of an application that was not given one.
///
/// Exists so that "no clipboard is wired up" is a named failure at the moment
/// of the Ctrl+V rather than a null dereference somewhere else, and so that
/// callers never have to hold a `Clipboard?`. Every operation throws
/// [ClipboardException] with the reason it was handed to them.
final class UnavailableClipboard implements Clipboard {
  const UnavailableClipboard([
    this.reason = 'this application was started without a clipboard; pass one '
        'through ApplicationOptions.clipboard',
  ]);

  final String reason;

  // `async` rather than a bare `throw`: the contract is that a failure arrives
  // as a rejected future, so a caller that stored the future and awaited it
  // later still sees the error instead of taking it at the call site.
  @override
  Future<String?> readText() async =>
      throw ClipboardException(operation: 'readText', reason: reason);

  @override
  Future<void> writeText(String text) async =>
      throw ClipboardException(operation: 'writeText', reason: reason);
}
